// One-time (re-runnable) fetch of the app's web fonts for self-hosting.
//
// The app, landing page and About page previously loaded four families from the
// Google Fonts CDN, which meant the whole "Rulebook" look collapsed to system
// fonts when offline or on flaky game-store wifi — exactly where this PWA is
// used. This downloads the Latin woff2 subsets Google itself serves and writes
// a local `public/fonts/fonts.css`, so the fonts are served from our own origin
// (and cached by the service worker). Run: `node scripts/fetch-fonts.mjs`.
//
// Not part of the build — the woff2 files and fonts.css are committed. Re-run
// only to add a weight or refresh the files.

import { mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const outDir = resolve(here, '..', 'public', 'fonts');
mkdirSync(outDir, { recursive: true });

// Matches the exact families/weights index.html and landing.html request.
const CSS2 =
  'https://fonts.googleapis.com/css2?family=Alegreya:ital,wght@0,400;0,500;0,700;1,400' +
  '&family=Alegreya+Sans:wght@400;500;700&family=IM+Fell+English:ital@0;1' +
  '&family=IM+Fell+English+SC&family=Pirata+One&display=swap';

// A desktop-Chrome UA makes Google serve woff2 (older UAs get ttf).
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

// English content — keep only the Latin subsets; drop cyrillic/greek/vietnamese.
const KEEP = new Set(['latin', 'latin-ext']);

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

const css = await (await fetch(CSS2, { headers: { 'User-Agent': UA } })).text();

// Each face is a `/* subset */` comment immediately followed by an @font-face.
const blockRe = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g;
const field = (body, name) => (body.match(new RegExp(name + '\\s*:\\s*([^;]+);')) || [])[1]?.trim();

const faces = [];
let m;
while ((m = blockRe.exec(css))) {
  const [, subset, body] = m;
  if (!KEEP.has(subset)) continue;
  const family = field(body, 'font-family').replace(/['"]/g, '');
  const style = field(body, 'font-style');
  const weight = field(body, 'font-weight');
  const unicodeRange = field(body, 'unicode-range');
  const url = (body.match(/url\((https:\/\/[^)]+\.woff2)\)/) || [])[1];
  if (!url) continue;
  const file = `${slug(family)}-${weight}-${style}-${subset}.woff2`;
  faces.push({ family, style, weight, unicodeRange, url, file });
}

if (faces.length === 0) throw new Error('Parsed no font faces — did the CSS2 format change?');

for (const f of faces) {
  const buf = Buffer.from(await (await fetch(f.url, { headers: { 'User-Agent': UA } })).arrayBuffer());
  writeFileSync(resolve(outDir, f.file), buf);
  console.log(`  ${f.file}  (${(buf.length / 1024).toFixed(1)} kB)`);
}

const cssOut =
  '/* Self-hosted app fonts (spec §5.2 / §12.4). Generated by\n' +
  '   scripts/fetch-fonts.mjs from the Google Fonts CSS2 API — Latin subsets\n' +
  '   only, font-display: swap. Do not edit by hand; re-run the script. */\n\n' +
  faces
    .map(
      (f) =>
        `@font-face {\n` +
        `  font-family: '${f.family}';\n` +
        `  font-style: ${f.style};\n` +
        `  font-weight: ${f.weight};\n` +
        `  font-display: swap;\n` +
        `  src: url('/fonts/${f.file}') format('woff2');\n` +
        `  unicode-range: ${f.unicodeRange};\n` +
        `}`,
    )
    .join('\n\n') +
  '\n';

writeFileSync(resolve(outDir, 'fonts.css'), cssOut);
console.log(`\nWrote public/fonts/fonts.css with ${faces.length} faces.`);
