// All user-facing UI copy lives here so a future translation pass is a
// single-file change. Game-content text (skill effects, injury text, etc.)
// lives in /src/data instead — this file is app-chrome only.

export const strings = {
  appName: 'Mordheim Campaign Manager',
  tagline: 'Warband & campaign bookkeeping',
  nav: {
    appShort: 'Mordheim',
    home: 'Home',
    warbands: 'Warbands',
    postBattle: 'Battle',
    trading: 'Trading',
    campaign: 'Campaign',
    rules: 'Rules',
    settings: 'Account',
    signIn: 'Sign in',
    signOut: 'Sign out',
  },
  common: {
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    back: 'Back',
    add: 'Add',
    gold: 'gc',
    dismiss: 'Dismiss',
    loading: 'Loading…',
    unsavedChanges: 'Unsaved changes',
    discard: 'Discard',
  },
  home: {
    title: 'Home',
    warbandCount: (n: number) => `${n} warband${n === 1 ? '' : 's'} in your account`,
    noCampaign: 'No campaign started yet',
    campaignSection: 'Campaign',
    startCampaignCta: 'Set up a campaign to start logging battles.',
    goToCampaign: 'Open Campaign Log',
    battleCount: (n: number) => `${n} battle${n === 1 ? '' : 's'} logged`,
    btbBadge: 'Border Town Burning',
    warbandsSection: 'Your Warbands',
    noWarbandsCta: 'Create your first warband to get started.',
    quickActionsSection: 'Quick Actions',
    viewCampaignLog: 'View Campaign Log',
    // Signed-out landing: the rules reference is fully usable without an account,
    // only warband/campaign data needs one.
    signedOutTitle: 'Browse the rules, or sign in to manage your warbands',
    signedOutBody:
      'The full Mordheim rules reference and every skill list are free to browse — no account needed. Sign in to create warbands, run the post-battle sequence, and track a campaign.',
    signInButton: 'Sign in',
    createAccountButton: 'Create an account',
    browseRules: 'Browse the Rules Reference',
    browseGallery: 'Browse Public Warbands',
    noAccountNeeded: 'No account needed',
  },
  rules: {
    title: 'Rules Reference',
    searchPlaceholder: 'Search rules…',
    allCategories: 'All',
    noResults: 'No rules match your search.',
    noEntriesInCategory: 'No entries in this category yet.',
    sourceLabel: 'Source',
    relatedSection: 'Related rules',
    resultCount: (n: number) => `${n} result${n === 1 ? '' : 's'}`,
  },
  report: {
    trigger: 'Report an issue on this page',
    heading: 'Report an issue',
    hint: 'What went wrong, or what looks incorrect? The page you are on and which build you are running are attached automatically.',
    placeholder: 'The Necromancer has no spells listed, but he is a wizard…',
    send: 'Send report',
    sending: 'Sending…',
    cancel: 'Cancel',
    thanks: 'Thanks — that has been logged.',
    failed: 'That could not be sent. Check your connection and try again.',
    attachedTo: (path: string) => `Attached: ${path}`,
  },

  settings: {
    title: 'Account',
    appearanceSection: 'Appearance',
    themeNames: {
      grimdark: 'Grimdark',
      parchment: 'Rulebook',
    },
    themeHints: {
      grimdark: 'Dark stone and ember. Easy on the eyes in a dim room.',
      parchment: 'Aged paper and black ink, like the printed book.',
    },
    dataSection: 'Your Data',
    exportButton: 'Export all data (.json)',
    importButton: 'Import data from file',
    importOverwriteWarning: 'Importing will overwrite all warbands and campaign data currently stored on this device. This cannot be undone. Continue?',
    importSuccess: 'Import complete.',
    importError: (message: string) => `Import failed: ${message}`,
    aboutSection: 'About',
    changelogLink: "What's New (Changelog)",
    accountSection: 'Your details',
    signedInAs: (email: string) => `Signed in as ${email}`,
    displayNameLabel: 'Display name',
    // Says where it shows up, because it is the one field here other people see.
    displayNameHint: 'Shown to your campaign-mates in standings and on any warband you make public.',
    displayNameSave: 'Save name',
    displayNameSaved: 'Name updated.',
    displayNameEmpty: 'Your display name cannot be empty.',
    signOutButton: 'Sign out',
    signedOutHint: 'Sign in to export or import your warband and campaign data.',
    adminSection: 'Admin',
    adminLink: 'Issue inbox & statistics',
    adminHint: 'Reported issues and aggregate numbers. Only you can see this.',
    signInButton: 'Sign in',
  },
  events: {
    section: 'Game nights',
    nextUp: 'Next up',
    today: 'today',
    tomorrow: 'tomorrow',
    inDays: (n: number) => `in ${n} days`,
    upcoming: 'Upcoming',
    past: 'Past',
    empty: 'No game nights scheduled yet. Anyone in the campaign can add one.',
    addButton: '+ Schedule a game night',
    titleLabel: 'What',
    titlePlaceholder: 'Game night — Session 5',
    whenLabel: 'When',
    locationLabel: 'Where',
    locationPlaceholder: 'The game store, back room',
    notesLabel: 'Notes',
    saveButton: 'Save event',
    deleteConfirm: (title: string) => `Delete "${title}"?`,
  },
  changelog: {
    title: "What's New",
  },
  auth: {
    loginTitle: 'Sign in',
    registerTitle: 'Create account',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    displayNameLabel: 'Display name',
    loginButton: 'Sign in',
    registerButton: 'Create account',
    loginSubmitting: 'Signing in…',
    registerSubmitting: 'Creating account…',
    noAccountPrompt: "Don't have an account?",
    hasAccountPrompt: 'Already have an account?',
    registerLink: 'Create one',
    loginLink: 'Sign in',
    connectionRequired: 'Mordheim Manager needs a live connection to Supabase — there is no offline mode.',
    forgotPasswordLink: 'Forgot your password?',
    forgotTitle: 'Reset your password',
    forgotIntro: "Enter the email you signed up with and we'll send you a link to set a new password.",
    forgotButton: 'Send reset link',
    forgotSubmitting: 'Sending…',
    // Deliberately the same whether or not the address exists, so this can't be
    // used to probe which emails have accounts.
    forgotSent:
      "If an account exists for that address, a reset link is on its way. Check your inbox — and your spam folder if it doesn't turn up.",
    backToLogin: 'Back to sign in',
    resetTitle: 'Choose a new password',
    resetIntro: 'Enter a new password for your account.',
    newPasswordLabel: 'New password',
    confirmPasswordLabel: 'Confirm new password',
    resetButton: 'Update password',
    resetSubmitting: 'Updating…',
    resetSuccess: 'Password updated. You are now signed in.',
    resetMismatch: 'Those passwords do not match.',
    resetTooShort: 'Password must be at least 6 characters.',
    resetNoSession:
      'This reset link is invalid or has expired. Request a new one from the sign-in screen.',
  },
  connection: {
    lost: "Connection to Supabase failed — your last change may not have saved. Check your connection and retry.",
  },
  weaponRules: {
    fullEntry: 'Full rules entry →',
    toggle: 'Weapon rules',
    costLabel: 'Cost',
    availabilityLabel: 'Availability',
    rangeLabel: 'Range',
    strengthLabel: 'Strength',
    specialRulesHeading: 'Special Rules',
    noSpecialRules: 'No special rules.',
    availabilityCommon: 'Common',
    availabilityRare: (n: number) => `Rare ${n}`,
  },
  warbandList: {
    title: 'Warbands',
    empty: 'No warbands yet. Create one to get started.',
    newWarband: '+ New Warband',
    ratingLabel: 'Rating',
    goldLabel: 'Gold',
    shardsLabel: 'Shards',
    myWarbandsTab: 'Mine',
    publicTab: 'Public Warbands',
    rulesTab: 'Rules',
    publicIntro: 'Warbands other players have chosen to share. Tap one to read its roster.',
    publicSearchPlaceholder: 'Search by warband, player or type',
    publicTypeFilter: 'Filter by warband type',
    publicAllTypes: 'All types',
    publicEmpty: "No public warbands yet. Set one of yours to public from its roster screen and it'll show up here.",
    publicNoMatches: 'Nothing matches that search.',
    publicCount: (n: number) => `${n} warband${n === 1 ? '' : 's'}`,
    // Only shown while more pages exist, so the search scope is never ambiguous.
    publicLoadedSoFar: (n: number) => `of ${n} loaded so far`,
    publicLoadMore: 'Load more',
  },
  newWarband: {
    title: 'New Warband',
    nameLabel: 'Warband name',
    namePlaceholder: 'e.g. Grubnik\'s Maneaters',
    typeLabel: 'Warband type',
    createButton: 'Create Warband',
    nameRequired: 'Give your warband a name first.',
  },
  roster: {
    heroesSection: 'Heroes',
    henchmenSection: 'Henchmen Groups',
    hiredSwordsSection: 'Hired Swords',
    noHeroes: 'No heroes yet.',
    noHenchmen: 'No henchmen groups yet.',
    // Every member of a group carries the same Experience total — saying "each"
    // stops it reading as the group's combined score.
    xpEach: (xp: number) => `${xp} XP each`,
    noHiredSwords: 'No hired swords yet.',
    addHero: '+ Add Hero',
    addHenchmen: '+ Add Henchmen',
    goldLabel: 'Gold',
    shardsLabel: 'Wyrdstone Shards',
    ratingLabel: 'Warband Rating',
    deleteWarband: 'Delete Warband',
    deleteWarbandCancel: 'Keep this warband',
    deleteWarbandTypeLabel: (name: string) => `Type ${name} to confirm`,
    deleteWarbandAction: 'Delete this warband',
    // Says what goes and what stays. "Cannot be undone" was both frightening
    // and, since 0009, no longer true — an operator can restore it.
    deleteWarbandImpact: (models: number, campaign: string | null) =>
      `This removes ${models} model${models === 1 ? '' : 's'} with their Experience, advances, injuries and equipment` +
      (campaign ? `, and drops the warband out of ${campaign} — its standings row goes with it.` : '.'),
    deleteWarbandKeeps: 'Battles already logged stay in the campaign history.',
    deleteWarbandRecoverable: 'Deleted warbands are kept, hidden, so this can be reversed on request.',
    addHiredSword: 'Hire a Hired Sword',
    slotFull: 'full',
    slotsUnlimited: 'No limit on this unit',
    slotsRemaining: (left: number, max: number) => `${left} of ${max} slots left`,
    startingXpLabel: (xp: number) => `Starting XP: ${xp}`,
    costVsTreasury: (cost: number, gold: number) => `Cost ${cost} gc · treasury ${gold} gc`,
    atMaxSize: (max: number) => `Warband is at its maximum size of ${max} models.`,
    warbandSizeWarning: (max: number) =>
      `This takes the warband past its maximum size of ${max} models. Add anyway?`,
    cannotRecruitMore: 'No room or no gold for more of these right now.',
    overLimitHint: (max: number) => `Only ${max} can be added right now.`,
    slotLimitWarning:(unitType: string, max: number) =>
      `Your warband already has the normal maximum of ${max} ${unitType}(s). Add another anyway?`,
    missNextGameBadge: 'Miss Next Game',
    deadBadge: 'Dead',
    capturedBadge: 'Captured',
    leftBadge: 'Left Warband',
    visitTrading: 'Visit Trading Post',
  },
  addHero: {
    title: 'Add Hero',
    pickSlot: 'Choose a hero type',
    nameLabel: 'Name',
    namePlaceholder: "e.g. Grubnik",
  },
  addHiredSword: {
    title: 'Hire a Hired Sword',
    pickType: 'Choose a Hired Sword',
    nameLabel: 'Name',
    namePlaceholder: 'e.g. Skalf One-Eye',
    nameRequired: 'Give your Hired Sword a name.',
    hireButton: 'Hire',
    upkeepLabel: 'Upkeep',
    perBattle: 'per battle',
    hiredByLabel: 'May be hired by',
    equipmentLabel: 'Comes with',
    specialRulesLabel: 'Special rules',
    notCountedHint: "Hired Swords don't count toward your maximum warband size.",
  },
  addHenchmen: {
    title: 'Add Henchmen',
    pickType: 'Choose a henchman type',
    groupNameLabel: 'Group name',
    groupNamePlaceholder: 'e.g. Gnoblar Mob',
    countLabel: 'Number of models',
    addToExisting: 'Add to an existing group instead',
    newGroup: 'Start a new group',
  },
  modelDetail: {
    statsSection: 'Characteristics',
    atMax: 'At racial max',
    atMaxLegend: 'Bold values sit at the racial maximum; the lower row is that maximum.',
    xpSection: 'Experience',
    xpTotal: 'Total XP',
    xpToNextAdvance: (remaining: number, threshold: number) =>
      `${remaining} XP to next advance (at ${threshold})`,
    xpAtAdvance: 'Ready for an advance!',
    xpMaxed: 'Maximum advances reached.',
    recordAdvance: 'Record Advance',
    advanceTypeStat: 'Characteristic Increase',
    advanceTypeSkill: 'New Skill',
    pickStat: 'Which characteristic increased?',
    pickSkillList: 'Which skill list?',
    pickSkillName: 'Skill name',
    skillNamePlaceholder: 'e.g. Strongman',
    skillBlockedSuffix: (reason: string) => ` — ${reason}`,
    skillPrerequisiteWarning: (text: string) => `Prerequisite: ${text}`,
    specialRulesSection: 'Special Rules',
    meleeFull: (max: number) =>
      `A warrior may carry at most ${max} close combat weapons, on top of his free dagger. Move one to the treasury first.`,
    missileFull: (max: number) =>
      `A warrior may carry at most ${max} different missile weapons (a brace of pistols counts as one). Move one to the treasury first.`,
    weaponSlots: (melee: number, maxMelee: number, missile: number, maxMissile: number) =>
      `Weapons carried: ${melee}/${maxMelee} close combat, ${missile}/${maxMissile} missile`,
    unstructuredNotes: 'Notes from the source',
    todoBadge: 'To do',
    skillsSection: 'Skills',
    noSkills: 'No skills learned yet.',
    spells: {
      // The heading itself comes from the list's kind — a priest prays rather
      // than casts — so these take the word rather than hardcoding "spell".
      none: (kind: string) => `No ${kind} known yet.`,
      allKnown: (kind: string) => `Knows every entry on the list — no ${kind} left to learn.`,
      rollButton: (die: string) => `Roll ${die}`,
      rollResult: (die: number, name: string) => `Rolled ${die}: ${name}.`,
      rerolled: (dice: string) => `Re-rolled ${dice} — already known.`,
      chooseInstead: 'Or choose from the list',
      chooseCount: (n: number) => `${n} available`,
      chooseThis: 'Learn this',
      remove: 'Remove',
    },
    injuriesSection: 'Injuries',
    noInjuries: 'No injuries recorded.',
    addInjury: '+ Add Injury',
    injuryNameLabel: 'Injury name',
    injuryEffectLabel: 'Effect',
    missNextGameLabel: 'Miss next game',
    equipmentSection: 'Equipment',
    noEquipment: 'Nothing equipped.',
    treasurySection: 'Warband Treasury',
    noTreasury: 'Treasury is empty.',
    moveToTreasury: 'Move to treasury',
    assignToModel: 'Assign here',
    buyEquipment: '+ Buy Equipment',
    hideShop: 'Hide Shop',
    shopGoldLabel: 'Warband Gold',
    statusLabel: 'Status',
    notesLabel: 'Notes',
    deleteModel: 'Remove from Warband',
    deleteModelConfirm: (name: string) => `Remove ${name} from the warband? This cannot be undone.`,
  },
  battle: {
    pickWarbandTitle: 'Battle',
    pickWarbandPrompt: 'Which warband is about to fight?',
    noWarbands: 'Create a warband first.',
    startBattleButton: 'Start Battle',
    preBattle: {
      title: 'Pre-Battle Setup',
      scenarioLabel: 'Scenario',
      scenarioPlaceholder: '—',
      rollRandomButton: 'Roll Random Scenario',
      randomRollResultLabel: (name: string) => `Rolled: ${name}`,
      scenarioPageHint: 'Full scenario rules: core rulebook p.85–92.',
      opponentNameLabel: 'Opponent',
      opponentNamePlaceholder: "e.g. Marius Dire's Undead",
      opponentWarbandLabel: "Opponent's warband (optional — links their roster to this battle)",
      opponentWarbandNone: 'No linked warband — paper roster',
      opponentGroupMine: 'My warbands',
      opponentGroupCampaign: 'In this campaign',
      noCampaignOpponents: 'No other warbands have been entered in your campaign yet.',
      notesLabel: 'Notes / battle plan',
      continueButton: 'Continue to During Battle',
      skipToPostBattle: 'Skip to Post-Battle Sequence',
    },
    duringBattle: {
      title: 'During Battle',
      turnLabel: 'Turn',
      eventLogSection: 'Event Log',
      addEventPlaceholder: 'e.g. Wyrdstone shard found near the fountain',
      addEvent: 'Add',
      noEvents: 'No events logged yet.',
      removeEvent: 'Remove',
      rosterSection: 'Quick Roster Reference',
      viewFullDetails: 'View full details',
      noEquipment: 'No equipment.',
      noSkills: 'No skills.',
      goToPostBattle: 'Go to Post-Battle Sequence',
      turnBackConfirm: (turn: number) => `Go back to turn ${turn}?`,
      markOutOfAction: 'Mark out of action',
      outOfActionMarked: 'Out of action',
      outOfActionCount: 'Out of action',
      oneFewerDown: 'One fewer out of action',
      oneMoreDown: 'One more out of action',
      carriedOverNotice:
        'Casualties marked during the battle have been filled in below. Adjust them if anything changed.',
    },
  },
  postBattle: {
    pickWarbandTitle: 'Post-Battle Sequence',
    pickWarbandPrompt: 'Which warband fought this battle?',
    noWarbands: 'Create a warband first.',
    startButton: 'Start Post-Battle Sequence',
    stepOf: (step: number, total: number) => `Step ${step} of ${total}`,
    next: 'Next',
    commitBattle: 'Commit Battle',
    undoLastBattle: 'Undo Last Battle',
    undoConfirm: 'Revert the warband and campaign log to how they were before the last post-battle sequence was committed?',
    battleInfo: {
      scenarioLabel: 'Scenario',
      scenarioCustom: 'Other / not listed…',
      scenarioCustomLabel: 'Scenario name',
      opponentsLabel: 'Opponent warband(s)',
      opponentsPlaceholder: 'e.g. Marius Dire\'s Undead',
      resultLabel: 'Result',
      win: 'Win',
      loss: 'Loss',
      draw: 'Draw',
      dateLabel: 'Date',
      underdogLabel: 'Underdog bonus (per surviving model)',
      underdogHint: 'From the rulebook\'s underdog table: 0 if the rating gap is 0-50, +1 for 51-75, +2 for 76-100, +3 for 101-150, +4 for 151-300, +5 for 301+.',
      notesLabel: 'Battle notes',
    },
    injuries: {
      sittingOut: 'Sitting out this game (missed last game\'s penalty).',
      outOfActionToggle: 'Taken out of action this battle',
      rollInjury: 'Roll on the injury table',
      rollD66Button: 'Roll D66',
      d66ResultLabel: (tens: number, units: number, name: string) => `Rolled ${tens} & ${units} (${tens}${units}): ${name}`,
      addAnotherRoll: '+ Add another roll (Multiple Injuries)',
      statusLabel: 'Resulting status',
      henchmenOutOfAction: 'Models taken out of action',
      henchmenDied: 'Of those, how many died? (D6 per model: 1-2 dead)',
      rollCasualtiesButton: 'Roll for Casualties',
      diceRollsLabel: (rolls: number[]) => `Rolls: ${rolls.join(', ')}`,
      diedCountResult: (died: number, total: number) => `${died} of ${total} died.`,
      hiredSwordLostHint: 'Hired Swords use the Henchmen rule: roll a D6, 1-2 = lost, 3-6 = survives.',
      hiredSwordLostToggle: 'Lost (D6 rolled 1-2)',
      rollD6Button: 'Roll D6',
      d6ResultLabel: (roll: number, lost: boolean) => `Rolled ${roll}: ${lost ? 'Lost' : 'Survives'}`,
      none: 'No one from this warband was taken out of action.',
    },
    experience: {
      title: 'Award Experience',
      xpAwarded: 'XP this battle',
      quickAwards: 'Quick awards',
      customAmount: 'Custom amount',
      survivesNote: 'Every participant gets +1 automatically for surviving — already included below.',
    },
    advances: {
      title: 'Resolve Advances',
      thresholdsIntro:
        'Only warriors who crossed an Experience box this battle appear here, and each gets exactly the advances they earned.',
      currentXp: 'Current XP',
      noneEligible: 'Nobody crossed an Experience box this battle, so there are no advances to record.',
      recordedOf: (recorded: number, due: number) =>
        recorded >= due ? `${due} of ${due} advances recorded` : `${recorded} of ${due} advances recorded`,
      removeHint: 'Tap to remove',
      statsAtMax: (stats: string) => `Already at racial maximum: ${stats}.`,
      allStatsMaxed: 'Every characteristic is at its racial maximum — only a new skill can be taken.',
      statAtMaxTitle: (stat: string) => `${stat} is already at its racial maximum.`,
      rerollNeeded: (stat: string) =>
        `${stat} is already at its maximum — roll again for a characteristic that can still be raised.`,
      ladsGotTalent: "That Lad's Got Talent",
      rollButton: 'Roll 2D6',
      rollResultLabel: (total: number) => `Rolled ${total} (2D6):`,
      subRollLabel: (roll: number) => `Roll again (D6): ${roll}`,
      chooseOnePrompt: 'Choose one:',
      specialResultHint: "This app doesn't support this result automatically yet — handle it manually.",
      manualEntryLabel: 'Or record manually',
    },
    deadCleanup: {
      title: 'Dead Models',
      none: 'No models were lost this battle.',
      equipmentFate: "What happens to their equipment?",
      toTreasury: 'Send to treasury',
      lost: 'Lost',
      henchmenWipedTitle: (name: string) => `${name} was wiped out`,
      deleteGroup: 'Remove this now-empty group from the roster',
    },
    income: {
      title: 'Income',
      exploration: {
        heading: 'Exploration',
        diceLabel: 'Dice to roll',
        diceHint: (heroes: number, won: boolean) =>
          `${heroes} surviving Hero${heroes === 1 ? '' : 'es'}${won ? ' + 1 for the win' : ''}. Add dice for skills or equipment that grant them.`,
        rollButton: 'Roll the dice',
        rerollButton: 'Roll again',
        editHint: 'Tap a die to change it — for physical dice, a re-roll, or an Elf Ranger’s +1/-1.',
        keepHint: (max: number) => `Only ${max} dice count. Tap to choose which ones.`,
        keptBadge: 'Counts',
        droppedBadge: 'Dropped',
        totalLine: (total: number, shards: number) =>
          `Total ${total} → ${shards} wyrdstone shard${shards === 1 ? '' : 's'}`,
        noMultiple: 'No doubles — nothing found beyond the wyrdstone.',
        foundLabel: 'You found',
        subRollButton: (dice: string) => `Roll ${dice}`,
        subRollResult: (roll: number, result: string) => `Rolled ${roll}: ${result}`,
        applyButton: 'Apply this result',
        clearButton: 'Undo this result',
        appliedGold: (gc: number) => `+${gc} gc added to the treasury.`,
        appliedShards: (n: number) => `+${n} extra shard${n === 1 ? '' : 's'}.`,
        manualNotice: 'The rest of this result is recorded in the battle notes for you to apply by hand.',
        persistentNotice: 'This carries into later games, so it is added to the warband’s notes too.',
        variantNotice: 'Your warband resolves this location differently — the outcome below is the one that applies to you.',
      },
      wyrdstoneFoundLabel: 'Wyrdstone shards found this battle',
      currentStash: (n: number) => `Current stash: ${n} shard${n === 1 ? '' : 's'}`,
      sellLabel: 'Shards to sell now',
      sellPricePreview: (gc: number) => `Sells for ${gc} gc`,
      keepRest: (n: number) => `${n} shard${n === 1 ? '' : 's'} will stay in the warband stash.`,
    },
    upkeep: {
      title: 'Upkeep & Recruiting',
      none: 'No Hired Swords to pay upkeep for.',
      payToggle: (fee: number) => `Pay upkeep (${fee} gc)`,
      insufficientGoldWarning: (needed: number, have: number) =>
        `Total upkeep due is ${needed} gc but the warband only has ${have} gc. You can still proceed — anyone left unpaid will leave the warband.`,
      goToTrading: 'Visit Trading Post',
    },
    confirm: {
      title: 'Confirm & Commit',
      summaryTitle: 'Summary of changes',
      noChanges: 'No changes staged.',
      commitHint: 'Committing writes this battle to the campaign log and updates the warband. You can undo the most recent commit from the roster screen.',
    },
  },
  trading: {
    pickWarbandTitle: 'Trading Post',
    pickWarbandPrompt: 'Which warband is shopping?',
    noWarbands: 'Create a warband first.',
    shopTab: 'Shop',
    rulesTab: 'Trading Rules',
    goldLabel: 'Gold',
    commonTab: 'Common',
    rareTab: 'Rare',
    buyButton: (cost: number) => `Buy (${cost} gc)`,
    groupPurchaseConfirm: (item: string, count: number, total: number) =>
      `Every model in a Henchmen group carries the same gear, so this buys ${count}x ${item} for ${total} gc. Continue?`,
    insufficientGoldConfirm: (cost: number, have: number) =>
      `This costs ${cost} gc but the warband only has ${have} gc. Buy it anyway?`,
    rarityLabel: (n: number) => `Rare ${n}`,
    rollHint: 'This item is found on a result of the Rare number shown, or higher. Roll for me, or roll 2D6 (plus any modifiers) yourself and report the result.',
    rollButton: 'Roll for this item',
    autoRollButton: 'Roll 2D6 for me',
    autoRollResultLabel: (total: number, found: boolean, bonus: number) =>
      bonus
        ? `Rolled ${total} + ${bonus} = ${total + bonus}: ${found ? 'Found it!' : "Didn't find it"}`
        : `Rolled ${total}: ${found ? 'Found it!' : "Didn't find it"}`,
    foundButton: 'Found it',
    notFoundButton: "Didn't find it",
    buyRareNoRollButton: 'Buy (no roll needed)',
    preFirstBattleHint:
      "This warband hasn't fought its first battle yet — per the rulebook, rare items can be bought freely while first assembling a warband. Rolling to find rare items only applies once the campaign is underway.",
    rollBonusHint: (bonus: number) => `Add this warband's +${bonus} bonus before comparing to the Rare number.`,
    priceLabel: 'Price to pay (fill in after rolling any variable dice)',
    confirmPurchase: 'Confirm Purchase',
    treasurySection: 'Treasury',
    treasuryEmpty: 'Nothing in the treasury yet. Buy something above, or it\'ll show up here after a battle.',
    treasuryHint: 'Assign items to a model from the warband roster.',
    sellButton: 'Sell',
    sellPriceLabel: 'Sell price',
    sellConfirm: (name: string, price: number) => `Sell ${name} for ${price} gc?`,
    exclusiveBadge: "Warband-exclusive",
  },
  campaign: {
    title: 'Campaign',
    logTab: 'Log',
    rulesTab: 'Campaign Rules',
    startTitle: 'Start a Campaign',
    startHint: "Set this up once — you can change it later. Battles you commit from the Post-Battle Sequence will log here automatically.",
    nameLabel: 'Campaign name',
    namePlaceholder: 'e.g. Border Town Burning 2026',
    usesBtbLabel: 'Uses Border Town Burning objectives',
    startButton: 'Start Campaign',
    notesLabel: 'Campaign notes',
    battleLogSection: 'Battle Log',
    noBattles: 'No battles logged yet. Play one from the Post-Battle tab.',
    unknownWarband: 'Unknown warband',
    win: 'Win',
    loss: 'Loss',
    draw: 'Draw',
    underdogBonusLabel: (n: number) => `Underdog bonus: +${n} per survivor`,
    wyrdstoneFoundLabel: (n: number) => `${n} wyrdstone shard${n === 1 ? '' : 's'} found`,
    goldChangeLabel: (n: number) => `${n >= 0 ? '+' : ''}${n} gc`,
    opponentsLabel: 'Opponents',
    casualtiesLabel: 'Casualties',
    notesForBattleLabel: 'Notes',
    btbSection: 'Border Town Burning Objectives',
    btbHint: 'Objectives stay private to you — no one else in the campaign can see them, even for a warband you share.',
    objectiveLabel: 'Objective',
    noObjective: 'None chosen',
    progressLabel: 'Progress (Campaign Points / notes)',
    progressPlaceholder: 'e.g. 12 CP — Prophecy Fulfilled x1',
    completedLabel: 'Objective completed',

    // --- Shared campaigns (spec 8.5) ---
    standingsTab: 'Standings',
    membersTab: 'Players',
    joinTitle: 'Join a Campaign',
    joinAnotherTitle: 'Join another campaign with a code',
    myCampaignsTitle: 'My Campaigns',
    myCampaignsLink: 'All my campaigns',
    inCampaignCount: (n: number) => `You're in ${n} campaigns`,
    myCampaignsEmpty: "You're not in any campaigns yet. Start one or join with a code.",
    activeBadge: 'Showing now',
    playersStat: 'Players',
    battlesStat: 'Battles',
    yourWarbandsStat: 'Your warbands',
    openActive: 'Open campaign',
    switchToThis: 'Switch to this campaign',
    startOrJoinLink: 'Start or join another campaign',
    startAnotherTitle: 'Start another campaign',
    startAnotherHint:
      'You can lead or play in as many campaigns as you like. Each keeps its own battle log, standings and players, and a warband belongs to one at a time.',
    personalBattlesSection: 'Your Battles',
    personalBattlesHint: "Battles you've fought outside a campaign.",
    joinHint: 'Got a code from your campaign leader? Enter it here.',
    joinCodeLabel: 'Join code',
    joinCodePlaceholder: 'MRDH-7F2K',
    joinButton: 'Join Campaign',
    joinFailed: "That code didn't work. Check it with your campaign leader.",
    joinedTitle: (name: string) => `Joined ${name}`,
    orDivider: 'or',
    switchCampaignLabel: 'Current campaign',
    shareCodeSection: 'Invite Players',
    shareCodeHint: 'Share this code so others can join. Anyone with it can enter the campaign.',
    copyCode: 'Copy',
    codeCopied: 'Copied',
    shareWhatsApp: 'WhatsApp',
    shareDiscord: 'Copy for Discord',
    shareDiscordCopied: 'Copied — paste it',
    inviteMessage: (campaignName: string, code: string, url: string) =>
      `Join my Mordheim campaign "${campaignName}" — join code ${code}. Sign up at ${url}, then go to Campaign › Players and paste the code.`,
    // Backticks render the code as inline code in Discord, so it stays legible
    // and survives being read off a phone.
    inviteMessageDiscord: (campaignName: string, code: string, url: string) =>
      `Join my Mordheim campaign **${campaignName}** — join code \`${code}\`\nSign up at ${url}, then go to Campaign › Players and paste the code.`,
    regenerateCode: 'New code',
    regenerateConfirm: 'Issue a new join code? The old one will stop working immediately.',
    leaderOnlyHint: 'Only the campaign leader can change these.',
    noCodeYet: 'No code yet',
    membersSection: 'Players',
    roleLeader: 'Leader',
    rolePlayer: 'Player',
    youSuffix: '(you)',
    unnamedPlayer: 'Unnamed player',
    removeMember: 'Remove',
    makeLeader: 'Make leader',
    makeLeaderConfirm: (name: string) =>
      `Hand leadership of this campaign to ${name}? You stay a player, and they can then rename it, regenerate the join code and remove members — including you.`,
    leaderCannotLeave:
      'You lead this campaign. Make someone else leader first, or it would be left with nobody who can manage it.',
    removeMemberConfirm: (name: string) => `Remove ${name} from the campaign? Their warbands will be unlinked from the standings.`,
    leaveCampaign: 'Leave campaign',
    leaveConfirm:
      'Leave this campaign? Your warbands are withdrawn from its standings — they stay yours, and you can rejoin with the code.',
    standingsSection: 'Standings',
    noStandings: 'No players yet.',
    noWarbandEntered: 'No warband entered',
    standingsWarband: 'Warband',
    standingsPlayer: 'Player',
    standingsRating: 'Rating',
    standingsRecord: 'W/L/D',
    viewRoster: 'View roster',

    // --- Warband sharing controls (roster screen) ---
    sharingSection: 'Campaign & Sharing',
    inCampaignLabel: 'Entered in campaign',
    notInCampaign: 'Not entered',
    visibilityLabel: 'Visible outside the campaign',
    visibilityPublic: 'Anyone signed in can view this roster',
    visibilityPrivate: 'Only you (and your campaign) can view this roster',
    campaignMatesAlwaysSee: 'Players in your campaign can always see a warband you enter, whatever this is set to.',
    noCampaignsToJoin: 'Start or join a campaign first to enter a warband in one.',

    // --- Read-only roster of another player's warband ---
    sharedRosterTitle: 'Shared Roster',
    sharedRosterReadOnly: "Read-only — this is another player's warband.",
    sharedRosterOwnHint: 'This is how the rest of the campaign sees your warband.',
    sharedRosterEditMine: 'Open the full roster',
    sharedRosterUnavailable: "You can't view this warband. It may be private, or you may have left the campaign.",
    sharedHeroes: 'Heroes',
    sharedHenchmen: 'Henchmen',
    sharedHiredSwords: 'Hired Swords',
    sharedNoEquipment: 'No equipment',
    sharedNoSkills: 'No skills',
    sharedSkillsLabel: 'Skills',
    sharedInjuriesLabel: 'Injuries',
  },
} as const;
