// All user-facing UI copy lives here so a future translation pass is a
// single-file change. Game-content text (skill effects, injury text, etc.)
// lives in /src/data instead — this file is app-chrome only.

export const strings = {
  appName: 'Mordheim Campaign Manager',
  tagline: 'Warband & campaign bookkeeping',
  nav: {
    appShort: 'Mordheim',
    home: 'Home',
    warbands: 'Warbands',
    postBattle: 'Battle',
    trading: 'Trading',
    campaign: 'Campaign',
    rules: 'Rules',
    settings: 'Account',
    signIn: 'Sign in',
    signOut: 'Sign out',
    // One line per tab, shown by the guided tour (§20.4). Kept beside the labels
    // so the tour and the nav can't describe different things.
    help: {
      home: 'Your dashboard — the active campaign, every warband at a glance, and quick links into the rest.',
      warbands: 'Build and manage your warbands here: heroes, henchmen and hired swords, their gear, XP and injuries.',
      postBattle: 'Run a game end to end — set up the scenario, track the fight, then the guided post-battle sequence.',
      trading: 'The Trading Post: buy common and rare equipment against your gold, and sell from the treasury.',
      campaign: 'Your campaigns — shared standings and battle log, game nights, awards, and the code to invite your group.',
      rules: 'The full rulebook, searchable and grouped by chapter, with a dice roller for the table.',
      settings: 'Your account: theme, display name, a full data backup, and sign out.',
    },
  },
  tour: {
    /** The floating ? control, and its accessible name. */
    open: 'How to use the app',
    title: 'Getting around',
    progress: (n: number, total: number) => `${n} / ${total}`,
    next: 'Next',
    back: 'Back',
    done: 'Done',
    skip: 'Skip',
  },
  dice: {
    title: 'Dice roller',
    rulesLink: 'Dice roller',
    rulesLinkHint: 'For a house rule or a moment the app does not model.',
    dieLabel: 'Die',
    soundToggle: 'Dice sound',
    soundStateOn: 'Sound on',
    soundStateOff: 'Sound off',
    countLabel: 'How many',
    modifierLabel: 'Modifier',
    rollButton: 'Roll',
    // D66 is a table index (tens then units), not a sum, so the modifier is
    // meaningless against it and the reading is shown as its two digits.
    d66Reading: (tens: number, units: number) => `${tens} then ${units}`,
    // "3, 5, 1  +2  = 11" — dice, then modifier, then total.
    breakdown: (rolls: number[], modifier: number) =>
      rolls.join(', ') + (modifier ? `  ${modifier > 0 ? '+' : ''}${modifier}` : ''),
    historyTitle: 'This session',
    historyEmpty: 'No rolls yet.',
    clearHistory: 'Clear',
  },
  compare: {
    title: 'Compare warbands',
    entry: 'Compare',
    pickLeft: 'First warband',
    pickRight: 'Second warband',
    choose: 'Choose a warband…',
    unavailable: 'That warband could not be loaded — it may be private, or you may have left its campaign.',
    ratingLabel: 'Rating',
    goldLabel: 'Gold',
    modelsLabel: 'Models',
    heroesLabel: 'Heroes',
    henchmenLabel: 'Henchmen',
    hiredSwordsLabel: 'Hired swords',
    pickPrompt: 'Pick two warbands to see their profiles side by side.',
    sameWarband: 'Pick two different warbands.',
  },
  common: {
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    remove: 'Remove',
    back: 'Back',
    add: 'Add',
    gold: 'gc',
    dismiss: 'Dismiss',
    loading: 'Loading…',
    unsavedChanges: 'Unsaved changes',
    discard: 'Discard',
  },
  discord: {
    cta: 'Questions or ideas? Join the Discord',
    aria: 'Join the Mordheim Manager Discord for questions and suggestions',
  },
  whatsNew: {
    title: "What's new",
    dismiss: 'Got it',
    seeAll: 'Full changelog',
    more: (n: number) => `+${n} more in the changelog`,
  },
  home: {
    title: 'Home',
    // A guided next-step card for a player who hasn't finished setting up — the
    // three activation stages (warband -> campaign -> battle) the funnel tracks.
    getStarted: {
      eyebrow: 'Getting started',
      steps: ['Warband', 'Campaign', 'Battle'],
      warband: {
        title: 'Create your first warband',
        body: "Pick a warband type and we'll fill a legal starter roster within your gold — rename, re-equip and adjust it however you like.",
        cta: 'Create a warband',
        to: '/warbands/new',
      },
      campaign: {
        title: 'Start or join a campaign',
        body: 'A campaign tracks standings, awards and rivalries across your group. Start your own, or join a friend’s with their code.',
        cta: 'Go to campaigns',
        to: '/campaigns',
      },
      battle: {
        title: 'Play your first battle',
        body: 'Set up the game, track it as you play, then let the post-battle wizard handle injuries, experience, advances and income — nothing miscounted.',
        cta: 'Start a battle',
        to: '/warbands',
      },
    },
    warbandCount: (n: number) => `${n} warband${n === 1 ? '' : 's'} in your account`,
    noCampaign: 'No campaign started yet',
    campaignSection: 'Campaign',
    startCampaignCta: 'Set up a campaign to start logging battles.',
    goToCampaign: 'Open Campaign Log',
    battleCount: (n: number) => `${n} battle${n === 1 ? '' : 's'} logged`,
    btbBadge: 'Border Town Burning',
    warbandsSection: 'Your Warbands',
    noWarbandsCta: 'Create your first warband to get started.',
    quickActionsSection: 'Quick Actions',
    viewCampaignLog: 'View Campaign Log',
    // Signed-out landing: the rules reference is fully usable without an account,
    // only warband/campaign data needs one.
    signedOutTitle: 'Browse the rules, or sign in to manage your warbands',
    signedOutBody:
      'The full Mordheim rules reference and every skill list are free to browse — no account needed. Sign in to create warbands, run the post-battle sequence, and track a campaign.',
    signInButton: 'Sign in',
    createAccountButton: 'Create an account',
    browseRules: 'Browse the Rules Reference',
    browseGallery: 'Browse Public Warbands',
    noAccountNeeded: 'No account needed',
  },
  rules: {
    title: 'Rules Reference',
    searchPlaceholder: 'Search rules…',
    allCategories: 'All',
    noResults: 'No rules match your search.',
    noEntriesInCategory: 'No entries in this category yet.',
    // Coarse groups above the chapter accordion (§ redesign). Fine chapters are
    // the accordion rows; these bundle them for a quick narrow.
    groupCore: 'Core Rules',
    groupMagic: 'Magic',
    groupPostBattle: 'Post-Battle',
    groupTrading: 'Trading',
    groupWarbands: 'Warbands & Scenarios',
    diceRoller: 'Dice roller',
    entryCount: (n: number) => `${n} rule${n === 1 ? '' : 's'}`,
    sourceLabel: 'Source',
    relatedSection: 'Related rules',
    resultCount: (n: number) => `${n} result${n === 1 ? '' : 's'}`,
  },
  report: {
    trigger: 'Report an issue on this page',
    heading: 'Report an issue',
    hint: 'What went wrong, or what looks incorrect? The page you are on and which build you are running are attached automatically.',
    placeholder: 'The Necromancer has no spells listed, but he is a wizard…',
    send: 'Send report',
    sending: 'Sending…',
    cancel: 'Cancel',
    thanks: 'Thanks — that has been logged.',
    failed: 'That could not be sent. Check your connection and try again.',
    attachedTo: (path: string) => `Attached: ${path}`,
  },

  comments: {
    section: 'Comments',
    signedOut: 'Sign in to read and leave comments.',
    placeholder: 'Leave a comment on this warband…',
    post: 'Post comment',
    posting: 'Posting…',
    empty: 'No comments yet.',
    by: (name: string, date: string) => `${name || 'A player'} · ${date}`,
    remove: 'Delete',
    removeConfirm: 'Delete this comment?',
    report: 'Report',
    reported: 'Reported',
    reportMessage: 'Reported gallery comment',
    failed: 'That could not be sent. Check your connection and try again.',
  },

  warbandAwards: {
    section: 'Awards & honours',
  },

  notFound: {
    title: 'Not found',
    heading: 'This page doesn’t exist',
    body: 'The link may be mistyped, or it points at something that has since been moved or removed.',
    home: 'Back to Home',
  },

  settings: {
    title: 'Account',
    appearanceSection: 'Appearance',
    themeNames: {
      grimdark: 'Grimdark',
      parchment: 'Rulebook',
    },
    themeHints: {
      grimdark: 'Dark stone and ember. Easy on the eyes in a dim room.',
      parchment: 'Aged paper and black ink, like the printed book.',
    },
    dataSection: 'Your Data',
    exportButton: 'Export all data (.json)',
    importButton: 'Import data from file',
    importOverwriteWarning: 'Importing will overwrite all warbands and campaign data currently stored on this device. This cannot be undone. Continue?',
    importSuccess: 'Import complete.',
    importError: (message: string) => `Import failed: ${message}`,
    notifications: {
      section: 'Notifications',
      hint: 'Get notified on this device about your campaigns — a reminder the day before a game night you’re going to, and when a campaign-mate logs a battle.',
      on: 'Notifications on',
      off: 'Turn on campaign notifications',
      denied: 'Notifications were blocked. You can re-enable them in your browser’s site settings, then try again.',
      blocked: 'Notifications are blocked for this site. Re-enable them in your browser’s site settings to turn reminders on.',
      unsupportedHint:
        'This device can’t receive push notifications. On iPhone or iPad, add the app to your Home Screen first, then reminders become available.',
    },
    aboutSection: 'About',
    changelogLink: "What's New (Changelog)",
    accountSection: 'Your details',
    signedInAs: (email: string) => `Signed in as ${email}`,
    displayNameLabel: 'Display name',
    // Says where it shows up, because it is the one field here other people see.
    displayNameHint: 'Shown to your campaign-mates in standings and on any warband you make public.',
    displayNameSave: 'Save name',
    displayNameSaved: 'Name updated.',
    displayNameEmpty: 'Your display name cannot be empty.',
    signOutButton: 'Sign out',
    signedOutHint: 'Sign in to export or import your warband and campaign data.',
    adminSection: 'Admin',
    adminLink: 'Issue inbox & statistics',
    adminHint: 'Reported issues and aggregate numbers. Only you can see this.',
    signInButton: 'Sign in',
  },
  events: {
    section: 'Game nights',
    nextUp: 'Next up',
    noneScheduled: 'No game night scheduled — tap to add one.',
    calendarTitle: 'Calendar',
    viewAsCalendar: 'View as calendar',
    viewAsList: 'View as list',
    previousMonth: 'Previous month',
    nextMonth: 'Next month',
    pickADay: 'Pick a day',
    nothingOnThisDay: 'Nothing scheduled on this day.',
    eventCount: (n: number) => `${n} game night${n === 1 ? '' : 's'}`,
    // Monday-first, matching the calendars this app's players actually use.
    weekdayInitials: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
    homeLink: 'Game nights',
    today: 'today',
    tomorrow: 'tomorrow',
    inDays: (n: number) => `in ${n} days`,
    upcoming: 'Upcoming',
    past: 'Past',
    empty: 'No game nights scheduled yet. Anyone in the campaign can add one.',
    addButton: '+ Schedule a game night',
    titleLabel: 'What',
    titlePlaceholder: 'Game night — Session 5',
    whenLabel: 'When',
    locationLabel: 'Where',
    locationPlaceholder: 'The game store, back room',
    notesLabel: 'Notes',
    saveButton: 'Save event',
    deleteConfirm: (title: string) => `Delete "${title}"?`,
    editButton: 'Edit',
    deleteButton: 'Delete this game night',
    deleteTypeLabel: (title: string) => `Type ${title} to confirm`,
    deleteImpact: 'The event is removed for everyone in the campaign. Battles already logged are unaffected.',
    alreadyHappened: 'This one has already happened.',
    organisedBy: (name: string) => `Added by ${name}`,
    rsvp: {
      heading: 'Who’s coming?',
      going: 'Going',
      maybe: 'Maybe',
      cant: 'Can’t',
      goingCount: (n: number) => `${n} going`,
      noneYet: 'No replies yet.',
      // Compact banner tally, e.g. "3 going · 1 maybe".
      bannerTally: (going: number, maybe: number) => {
        const parts: string[] = [];
        if (going > 0) parts.push(`${going} going`);
        if (maybe > 0) parts.push(`${maybe} maybe`);
        return parts.join(' · ');
      },
    },
  },
  changelog: {
    title: "What's New",
  },
  auth: {
    loginTitle: 'Sign in',
    registerTitle: 'Create account',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    displayNameLabel: 'Display name',
    loginButton: 'Sign in',
    registerButton: 'Create account',
    loginSubmitting: 'Signing in…',
    registerSubmitting: 'Creating account…',
    noAccountPrompt: "Don't have an account?",
    hasAccountPrompt: 'Already have an account?',
    registerLink: 'Create one',
    loginLink: 'Sign in',
    connectionRequired: 'Mordheim Manager needs a live connection to Supabase — there is no offline mode.',
    forgotPasswordLink: 'Forgot your password?',
    forgotTitle: 'Reset your password',
    forgotIntro: "Enter the email you signed up with and we'll send you a link to set a new password.",
    forgotButton: 'Send reset link',
    forgotSubmitting: 'Sending…',
    // Deliberately the same whether or not the address exists, so this can't be
    // used to probe which emails have accounts.
    forgotSent:
      "If an account exists for that address, a reset link is on its way. Check your inbox — and your spam folder if it doesn't turn up.",
    backToLogin: 'Back to sign in',
    resetTitle: 'Choose a new password',
    resetIntro: 'Enter a new password for your account.',
    newPasswordLabel: 'New password',
    confirmPasswordLabel: 'Confirm new password',
    resetButton: 'Update password',
    resetSubmitting: 'Updating…',
    resetSuccess: 'Password updated. You are now signed in.',
    resetMismatch: 'Those passwords do not match.',
    resetTooShort: 'Password must be at least 6 characters.',
    resetNoSession:
      'This reset link is invalid or has expired. Request a new one from the sign-in screen.',
  },
  connection: {
    lost: "Connection to Supabase failed — your last change may not have saved. Check your connection and retry.",
  },
  weaponRules: {
    fullEntry: 'Full rules entry →',
    toggle: 'Weapon rules',
    costLabel: 'Cost',
    availabilityLabel: 'Availability',
    rangeLabel: 'Range',
    strengthLabel: 'Strength',
    specialRulesHeading: 'Special Rules',
    noSpecialRules: 'No special rules.',
    availabilityCommon: 'Common',
    availabilityRare: (n: number) => `Rare ${n}`,
  },
  warbandList: {
    title: 'Warbands',
    empty: 'No warbands yet. Create one to get started.',
    newWarband: '+ New Warband',
    ratingLabel: 'Rating',
    goldLabel: 'Gold',
    shardsLabel: 'Shards',
    myWarbandsTab: 'Mine',
    publicTab: 'Public Warbands',
    rulesTab: 'Rules',
    publicIntro: 'Warbands other players have chosen to share. Tap one to read its roster.',
    publicSearchPlaceholder: 'Search by warband, player or type',
    publicTypeFilter: 'Filter by warband type',
    publicAllTypes: 'All types',
    publicEmpty: "No public warbands yet. Set one of yours to public from its roster screen and it'll show up here.",
    publicNoMatches: 'Nothing matches that search.',
    publicCount: (n: number) => `${n} warband${n === 1 ? '' : 's'}`,
    // Only shown while more pages exist, so the search scope is never ambiguous.
    publicLoadedSoFar: (n: number) => `of ${n} loaded so far`,
    publicLoadMore: 'Load more',
  },
  newWarband: {
    title: 'New Warband',
    nameLabel: 'Warband name',
    namePlaceholder: 'e.g. Grubnik\'s Maneaters',
    typeLabel: 'Warband type',
    typePlaceholder: 'Choose a warband type…',
    typeSearchPlaceholder: 'Search warbands…',
    typeNoMatches: 'No warband matches that.',
    createButton: 'Create Warband',
    nameRequired: 'Give your warband a name first.',
    customSectionLabel: 'Your custom types',
    manageCustomLink: 'Manage custom types',
    quickBuildLabel: 'Quick-build a starter roster',
    quickBuildHint: 'Fills a legal starting warband you can change afterwards, instead of an empty roster.',
    quickBuildPreview: (summary: string) => `Will add: ${summary}`,
  },
  customWarbands: {
    title: 'Custom warband types',
    entry: 'Custom warband types',
    entryHint: 'Homebrew and house-rule warbands, cloned from an existing one.',
    intro:
      "Clone a warband and reassign its name and limits — house rules and homebrew, built on the rulebook's own numbers, not invented. Synced to your account.",
    baseLabel: 'Clone from',
    nameLabel: 'Custom type name',
    namePlaceholder: 'e.g. Reikland Free Company',
    create: 'Create custom type',
    creating: 'Creating…',
    createFailed: 'Could not create the custom type. Try again.',
    empty: 'No custom types yet. Clone one above to start.',
    clonedFrom: (base: string) => `Cloned from ${base}`,
    edit: 'Edit',
    remove: 'Delete',
    removeConfirm: (name: string) =>
      `Delete “${name}”? Warbands already built from it keep the stats they have.`,
    editTitle: 'Edit custom type',
    notFound: 'That custom type no longer exists.',
    startingGold: 'Starting gold',
    minSize: 'Minimum size',
    maxSize: 'Maximum size',
    unlimited: 'unlimited',
    heroesHeading: 'Hero types',
    henchmenHeading: 'Henchmen types',
    unitNameLabel: 'Name',
    unitMaxLabel: 'Max',
    save: 'Save changes',
    saving: 'Saving…',
    savedNote: 'Saved.',
    limitHint: 'Leave a maximum blank for unlimited.',
  },
  /**
   * The printable roster sheet. Field names follow the official Games Workshop
   * sheet (1999) so anyone who has filled one in by hand knows where to look —
   * "Skills, injuries, etc" is its wording, not ours.
   */
  print: {
    rosterLink: 'Print roster sheet',
    // Says what it is for, because the obvious objection is the cost of ink and
    // the answer is that recognising the model is the point of carrying a sheet.
    includePhotos: 'Include photos — helps match a warrior to the model on the table',
    title: 'Roster sheet',
    printAction: 'Print / Save as PDF',
    hint: 'In the print dialog, pick "Save as PDF" as the destination to keep a copy.',
    warbandName: 'Warband name',
    warbandType: 'Warband type',
    player: 'Player',
    heroes: 'Heroes',
    hiredSwords: 'Hired Swords',
    henchmen: 'Henchmen',
    name: 'Name',
    type: 'Type',
    number: 'Number',
    experience: 'Experience',
    groupExperience: 'Group experience',
    equipment: 'Equipment',
    skillsInjuries: 'Skills, injuries, etc',
    specialRules: 'Special rules',
    storedEquipment: 'Stored equipment',
    treasury: 'Treasury',
    goldCrowns: 'Gold crowns',
    wyrdstoneShards: 'Wyrdstone shards',
    warbandRating: 'Warband rating',
    totalExperience: 'Total experience',
    // The original prints "Members ( ) x 5". That arithmetic only holds while
    // every model is a normal one, so the label names the large creatures when
    // there are any rather than showing a sum that doesn't add up.
    membersLine: (models: number, largeCreatures: number) =>
      largeCreatures > 0
        ? `Members (${models}) x 5, of which ${largeCreatures} large x 20`
        : `Members (${models}) x 5`,
    rating: 'Rating',
    notes: 'Notes',
    leader: 'Leader',
    missNextGame: 'Misses next game',
    // Dated because a roster sheet goes stale the moment you finish a game, and
    // two printouts in a folder are otherwise impossible to tell apart.
    printedOn: (date: string) => `Printed ${date}`,
    nothingRecruited: 'Nothing recruited yet.',
    none: '—',
    // The rules glossary printed after the roster, so the sheet stands on its
    // own at the table.
    referenceTitle: 'Rules reference',
    referenceHint: 'The rules for every weapon, skill and special rule this warband uses — so you can leave the book at home.',
    referenceEquipment: 'Weapons & equipment',
    referenceSkills: 'Skills',
    referenceSpells: 'Spells & prayers',
    referenceSpecialRules: 'Special rules',
  },

  photo: {
    section: 'Warband photo',
    modelSection: 'Photo',
    add: 'Add a photo',
    replace: 'Replace photo',
    remove: 'Remove',
    uploading: 'Uploading…',
    removeConfirm: 'Remove this photo? The warband and its roster are untouched.',
    alt: (name: string) => `${name} — group shot`,
    // Says where it shows up and who can see it, because "public" here means
    // something narrower than the gallery's own visibility (§11.5).
    hint: 'Shown on your roster, the warband list and — if this warband is public — the gallery. Only signed-in players can see it. Photos are resized on your device before uploading.',
  },

  roster: {
    heroesSection: 'Heroes',
    henchmenSection: 'Henchmen Groups',
    hiredSwordsSection: 'Hired Swords',
    // Compact loadout summary on each roster card (names only — no cost or rarity).
    weaponsLabel: 'Weapons',
    skillsLabel: 'Skills',
    rulesLabel: 'Rules',
    // Shareable warband card (canvas image for Discord/group chats).
    card: {
      button: 'Share card',
      hint: 'A clean card image of this warband — for pasting into Discord or a group chat.',
      generating: 'Building card…',
      download: 'Download',
      share: 'Share',
      regenerate: 'Rebuild',
      failed: 'Could not build the card. Try again.',
      alt: (name: string) => `Shareable card for ${name}`,
    },
    // Warband health / legality check panel.
    health: {
      title: 'Warband check',
      allClear: 'All legal — nothing outstanding.',
      unresolved: "Can't check this warband — its type isn't loaded (a custom type still syncing, or one that was removed).",
      overSize: (n: number, max: number) => `Over the maximum warband size — ${n} of ${max} models.`,
      understrength: (n: number, min: number) =>
        `Understrength — ${n} models, below the ${min}-model minimum. Recruit before your next game.`,
      overUnit: (unit: string, n: number, max: number) =>
        `Too many ${unit} — ${n} of a maximum ${max}.`,
      advancesReady: (names: string) => `Advance ready to apply: ${names}.`,
      closeToAdvance: (names: string) => `Close to an advance: ${names}.`,
      xpAway: (name: string, n: number) => `${name} (${n} XP)`,
      upkeep: (n: number) => `Upkeep next battle: ${n} gc for Hired Swords.`,
    },
    noHeroes: 'No heroes yet.',
    noHenchmen: 'No henchmen groups yet.',
    // Every member of a group carries the same Experience total — saying "each"
    // stops it reading as the group's combined score.
    xpEach: (xp: number) => `${xp} XP each`,
    noHiredSwords: 'No hired swords yet.',
    addHero: '+ Add Hero',
    addHenchmen: '+ Add Henchmen',
    goldLabel: 'Gold',
    shardsLabel: 'Wyrdstone Shards',
    ratingLabel: 'Warband Rating',
    ratingHistoryTitle: 'Rating over time',
    ratingHistorySingle: (r: number) => `Rating ${r}. The chart appears once this warband's rating has changed at least once.`,
    ratingHistoryLabel: (min: number, max: number, now: number) =>
      `Rating over time, from ${min} to ${max}, currently ${now}.`,
    ratingHistoryLow: (r: number) => `low ${r}`,
    ratingHistoryHigh: (r: number) => `high ${r}`,
    deleteWarband: 'Delete Warband',
    deleteWarbandCancel: 'Keep this warband',
    deleteWarbandTypeLabel: (name: string) => `Type ${name} to confirm`,
    deleteWarbandAction: 'Delete this warband',
    // Says what goes and what stays. "Cannot be undone" was both frightening
    // and, since 0009, no longer true — an operator can restore it.
    deleteWarbandImpact: (models: number, campaign: string | null) =>
      `This removes ${models} model${models === 1 ? '' : 's'} with their Experience, advances, injuries and equipment` +
      (campaign ? `, and drops the warband out of ${campaign} — its standings row goes with it.` : '.'),
    deleteWarbandKeeps: 'Battles already logged stay in the campaign history.',
    deleteWarbandCampaignWarning: (campaign: string) =>
      `This warband is entered in ${campaign}.`,
    deleteWarbandCampaignAck: (campaign: string) =>
      `I understand this removes it from ${campaign}'s standings.`,
    deleteWarbandRecoverable: 'Deleted warbands are kept, hidden, so this can be reversed on request.',
    addHiredSword: 'Hire a Hired Sword',
    slotFull: 'full',
    slotsUnlimited: 'No limit on this unit',
    slotsRemaining: (left: number, max: number) => `${left} of ${max} slots left`,
    startingXpLabel: (xp: number) => `Starting XP: ${xp}`,
    costVsTreasury: (cost: number, gold: number) => `Cost ${cost} gc · treasury ${gold} gc`,
    atMaxSize: (max: number) => `Warband is at its maximum size of ${max} models.`,
    warbandSizeWarning: (max: number) =>
      `This takes the warband past its maximum size of ${max} models. Add anyway?`,
    cannotRecruitMore: 'No room or no gold for more of these right now.',
    overLimitHint: (max: number) => `Only ${max} can be added right now.`,
    slotLimitWarning:(unitType: string, max: number) =>
      `Your warband already has the normal maximum of ${max} ${unitType}(s). Add another anyway?`,
    missNextGameBadge: 'Miss Next Game',
    deadBadge: 'Dead',
    capturedBadge: 'Captured',
    leftBadge: 'Left Warband',
    visitTrading: 'Visit Trading Post',
  },
  addHero: {
    title: 'Add Hero',
    pickSlot: 'Choose a hero type',
    nameLabel: 'Name',
    namePlaceholder: "e.g. Grubnik",
  },
  addHiredSword: {
    title: 'Hire a Hired Sword',
    pickType: 'Choose a Hired Sword',
    nameLabel: 'Name',
    namePlaceholder: 'e.g. Skalf One-Eye',
    nameRequired: 'Give your Hired Sword a name.',
    hireButton: 'Hire',
    upkeepLabel: 'Upkeep',
    perBattle: 'per battle',
    hiredByLabel: 'May be hired by',
    equipmentLabel: 'Comes with',
    specialRulesLabel: 'Special rules',
    notCountedHint: "Hired Swords don't count toward your maximum warband size.",
  },
  addHenchmen: {
    title: 'Add Henchmen',
    pickType: 'Choose a henchman type',
    groupNameLabel: 'Group name',
    groupNamePlaceholder: 'e.g. Gnoblar Mob',
    countLabel: 'Number of models',
    addToExisting: 'Add to an existing group instead',
    newGroup: 'Start a new group',
  },
  modelDetail: {
    nameLabel: 'Name',
    nicknameLabel: 'Nickname',
    nicknamePlaceholder: 'e.g. One-Eye',
    equipmentHistory: 'Equipment history',
    equipmentActions: {
      acquired: 'Gained',
      lost: 'Lost',
      sold: 'Sold',
      destroyed: 'Destroyed',
    } as Record<'acquired' | 'lost' | 'sold' | 'destroyed', string>,
    logBought: (price: number) => `Bought for ${price} gc`,
    logMovedToTreasury: 'Moved to treasury',
    logFromTreasury: 'Assigned from treasury',
    logFellInBattle: 'Lost when the model fell',
    statsSection: 'Characteristics',
    atMax: 'At racial max',
    atMaxLegend: 'Bold values sit at the racial maximum; the lower row is that maximum.',
    xpSection: 'Experience',
    xpTotal: 'Total XP',
    xpToNextAdvance: (remaining: number, threshold: number) =>
      `${remaining} XP to next advance (at ${threshold})`,
    xpAtAdvance: 'Ready for an advance!',
    xpMaxed: 'Maximum advances reached.',
    recordAdvance: 'Record Advance',
    advanceTypeStat: 'Characteristic Increase',
    advanceTypeSkill: 'New Skill',
    pickStat: 'Which characteristic increased?',
    pickSkillList: 'Which skill list?',
    pickSkillName: 'Skill name',
    skillNamePlaceholder: 'e.g. Strongman',
    skillBlockedSuffix: (reason: string) => ` — ${reason}`,
    skillPrerequisiteWarning: (text: string) => `Prerequisite: ${text}`,
    specialRulesSection: 'Special Rules',
    meleeFull: (max: number) =>
      `A warrior may carry at most ${max} close combat weapons, on top of his free dagger. Move one to the treasury first.`,
    missileFull: (max: number) =>
      `A warrior may carry at most ${max} different missile weapons (a brace of pistols counts as one). Move one to the treasury first.`,
    weaponSlots: (melee: number, maxMelee: number, missile: number, maxMissile: number) =>
      `Weapons carried: ${melee}/${maxMelee} close combat, ${missile}/${maxMissile} missile`,
    unstructuredNotes: 'Notes from the source',
    todoBadge: 'To do',
    skillsSection: 'Skills',
    noSkills: 'No skills learned yet.',
    // Hand-editing skills/spells/advances (§4.2.1).
    addSkill: 'Add skill',
    removeSkillAction: 'Remove skill',
    removeSkillPrompt: (skill: string, model: string) => `Remove ${skill} from ${model}?`,
    removeSkillImpact: (model: string, items: string) =>
      `${model} is carrying ${items} under this skill; it will be flagged as ineligible on the roster.`,
    removeSpellAction: 'Remove',
    removeSpellPrompt: (spell: string, model: string) => `Remove ${spell} from ${model}?`,
    advancesSection: 'Advances',
    noAdvances: 'No advances recorded yet.',
    advanceStatLabel: (detail: string) => `Characteristic — ${detail}`,
    advanceSkillLabel: (detail: string) => `New skill — ${detail}`,
    removeAdvanceAction: 'Remove advance',
    removeAdvancePrompt: (model: string) => `Remove this advance from ${model}'s record?`,
    removeAdvanceNote:
      'This removes the advance from the record. It does not change the statline — edit that directly if needed.',
    removeAdvanceGrantOption: (grant: string) => `Also remove the granted skill or spell: ${grant}`,
    ineligibleEquipmentWarning: (items: string) =>
      `Not on this model's equipment list: ${items}. Unassign it, or re-add a skill that allows it.`,
    removedToast: (what: string) => `Removed: ${what}`,
    spells: {
      // The heading itself comes from the list's kind — a priest prays rather
      // than casts — so these take the word rather than hardcoding "spell".
      none: (kind: string) => `No ${kind} known yet.`,
      allKnown: (kind: string) => `Knows every entry on the list — no ${kind} left to learn.`,
      rollButton: (die: string) => `Roll ${die}`,
      rollResult: (die: number, name: string) => `Rolled ${die}: ${name}.`,
      rerolled: (dice: string) => `Re-rolled ${dice} — already known.`,
      chooseInstead: 'Or choose from the list',
      chooseCount: (n: number) => `${n} available`,
      chooseThis: 'Learn this',
      remove: 'Remove',
    },
    injuriesSection: 'Injuries',
    noInjuries: 'No injuries recorded.',
    addInjury: '+ Add Injury',
    injuryNameLabel: 'Injury name',
    injuryEffectLabel: 'Effect',
    missNextGameLabel: 'Miss next game',
    equipmentSection: 'Equipment',
    noEquipment: 'Nothing equipped.',
    treasurySection: 'Warband Treasury',
    noTreasury: 'Treasury is empty.',
    moveToTreasury: 'Move to treasury',
    assignToModel: 'Assign here',
    buyEquipment: '+ Buy Equipment',
    hideShop: 'Hide Shop',
    shopGoldLabel: 'Warband Gold',
    statusLabel: 'Status',
    notesLabel: 'Notes',
    deleteModel: 'Remove from Warband',
    deleteModelConfirm: (name: string) => `Remove ${name} from the warband? This cannot be undone.`,
  },
  battle: {
    pickWarbandTitle: 'Battle',
    pickWarbandPrompt: 'Which warband is about to fight?',
    noWarbands: 'Create a warband first.',
    startBattleButton: 'Start Battle',
    preBattle: {
      title: 'Pre-Battle Setup',
      scenarioLabel: 'Scenario',
      scenarioPlaceholder: '—',
      rollRandomButton: 'Suggest a scenario',
      randomRollResultLabel: (name: string) => `Suggested: ${name} — keep it or pick another above.`,
      scenarioPageHint: 'Full scenario rules: core rulebook p.85–92.',
      opponentNameLabel: 'Opponent',
      opponentNamePlaceholder: "e.g. Marius Dire's Undead",
      opponentWarbandLabel: "Opponent's warband (optional — links their roster to this battle)",
      opponentWarbandNone: 'No linked warband — paper roster',
      opponentGroupMine: 'My warbands',
      opponentGroupCampaign: 'In this campaign',
      noCampaignOpponents: 'No other warbands have been entered in your campaign yet.',
      fairPairing: {
        toggle: 'Suggest a fair match',
        heading: 'Closest in strength first',
        myRating: (n: number) => `Your rating: ${n}`,
        even: 'Even match',
        theyFavoured: (n: number) => `+${n} — they're favoured, you're the underdog`,
        youFavoured: (n: number) => `−${n} — you're favoured`,
        ratingLabel: (n: number) => `Rating ${n}`,
        pick: 'Pick',
        picked: 'Selected',
        noneRated: 'No opponents with a known rating to compare yet.',
      },
      setup: {
        heading: 'Scenario setup',
        players: (mode: string) => `Players: ${mode}`,
        awardsHeading: 'Experience on offer',
        fullRules: 'Full scenario rules',
        mapAlt: (name: string) => `${name} deployment map`,
      },
      notesLabel: 'Notes / battle plan',
      continueButton: 'Continue to During Battle',
      skipToPostBattle: 'Skip to Post-Battle Sequence',
      restore: {
        title: 'Resume the battle in progress?',
        since: (when: string) =>
          when
            ? `Started ${when}. Your during-battle marks, tallies and notes were saved.`
            : 'Your during-battle marks, tallies and notes were saved.',
        resume: 'Resume battle',
        discard: 'Discard and start over',
      },
    },
    duringBattle: {
      title: 'During Battle',
      turnLabel: 'Turn',
      diceRoller: 'Dice roller',
      injury: {
        section: 'Injury rolls',
        hint: 'Roll a downed model’s result, or a hero’s lasting injury — each one is added to the event log.',
        rollCombat: 'Wound result (D6)',
        rollSerious: 'Serious injury (D66)',
        knockedDown: 'Knocked down',
        stunned: 'Stunned',
        outOfAction: 'Out of action',
        combatLog: (roll: number, result: string) => `Wound result (${roll}): ${result}`,
        seriousLog: (key: string, name: string) => `Serious injury (${key}): ${name}`,
        logged: 'Logged to events.',
      },
      rout: {
        section: 'Rout test',
        status: (down: number, total: number, pct: number) =>
          `${down} of ${total} out of action (${pct}%)`,
        safe: 'Below 25% — no rout test needed.',
        required: 'A quarter of the warband is down — take a Rout test at the start of your turn.',
        bestLd: (n: number) => `Best Leadership on the table: ${n}`,
        roll: 'Roll rout test (2D6)',
        passLog: (total: number, ld: number) => `Rout test passed (rolled ${total} vs Ld ${ld})`,
        failLog: (total: number, ld: number) => `Rout test FAILED (rolled ${total} vs Ld ${ld}) — the warband routs`,
      },
      eventLogSection: 'Event Log',
      addEventPlaceholder: 'e.g. Wyrdstone shard found near the fountain',
      addEvent: 'Add',
      noEvents: 'No events logged yet.',
      removeEvent: 'Remove',
      rosterSection: 'Quick Roster Reference',
      viewFullDetails: 'View full details',
      noEquipment: 'No equipment.',
      noSkills: 'No skills.',
      goToPostBattle: 'Go to Post-Battle Sequence',
      turnBackConfirm: (turn: number) => `Go back to turn ${turn}?`,
      markOutOfAction: 'Mark out of action',
      outOfActionMarked: 'Out of action',
      outOfActionCount: 'Out of action',
      oneFewerDown: 'One fewer out of action',
      oneMoreDown: 'One more out of action',
      enemyOoaLabel: 'Enemies taken out',
      enemyOoaTotal: (n: number) =>
        `${n} enemy model${n === 1 ? '' : 's'} taken out this battle — feeds each hero's Experience.`,
      wyrdstoneLabel: 'Wyrdstone carried',
      wyrdstoneToggle: 'Wyrdstone counters',
      wyrdstoneTotal: (n: number) => `${n} shard${n === 1 ? '' : 's'} carried`,
      wyrdstoneDropped: (n: number) => `${n} shard${n === 1 ? '' : 's'} dropped`,
      wyrdstoneDroppedHint: 'Tap + on whoever picked them up, or mark them lost.',
      wyrdstoneMarkLost: 'Mark lost',
      carriedOverNotice:
        'Casualties marked during the battle have been filled in below. Adjust them if anything changed.',
    },
  },
  postBattle: {
    pickWarbandTitle: 'Post-Battle Sequence',
    pickWarbandPrompt: 'Which warband fought this battle?',
    noWarbands: 'Create a warband first.',
    startButton: 'Start Post-Battle Sequence',
    stepOf: (step: number, total: number) => `Step ${step} of ${total}`,
    next: 'Next',
    commitBattle: 'Commit Battle',
    undoLastBattle: 'Undo Last Battle',
    undoConfirm: 'Revert the warband and campaign log to how they were before the last post-battle sequence was committed?',
    battleInfo: {
      scenarioLabel: 'Scenario',
      scenarioCustom: 'Other / not listed…',
      scenarioCustomLabel: 'Scenario name',
      opponentsLabel: 'Opponent warband(s)',
      opponentsPlaceholder: 'e.g. Marius Dire\'s Undead',
      resultLabel: 'Result',
      win: 'Win',
      loss: 'Loss',
      draw: 'Draw',
      dateLabel: 'Date',
      underdogLabel: 'Underdog bonus (per surviving model)',
      underdogHint: 'From the rulebook\'s underdog table: 0 if the rating gap is 0-50, +1 for 51-75, +2 for 76-100, +3 for 101-150, +4 for 151-300, +5 for 301+.',
      enemiesTakenOutLabel: 'Enemy models taken out',
      enemiesTakenOutHint: 'How many enemy models your warband took out of action this battle. Powers the campaign "Slayer" award; leave at 0 if you\'d rather not track it.',
      notesLabel: 'Battle notes',
    },
    injuries: {
      sittingOut: 'Sitting out this game (missed last game\'s penalty).',
      outOfActionToggle: 'Taken out of action this battle',
      rollInjury: 'Roll on the injury table',
      rollD66Button: 'Roll D66',
      d66ResultLabel: (tens: number, units: number, name: string) => `Rolled ${tens} & ${units} (${tens}${units}): ${name}`,
      addAnotherRoll: '+ Add another roll (Multiple Injuries)',
      statusLabel: 'Resulting status',
      henchmenOutOfAction: 'Models taken out of action',
      henchmenDied: 'Of those, how many died? (D6 per model: 1-2 dead)',
      rollCasualtiesButton: 'Roll for Casualties',
      diceRollsLabel: (rolls: number[]) => `Rolls: ${rolls.join(', ')}`,
      diedCountResult: (died: number, total: number) => `${died} of ${total} died.`,
      hiredSwordLostHint: 'Hired Swords use the Henchmen rule: roll a D6, 1-2 = lost, 3-6 = survives.',
      hiredSwordLostToggle: 'Lost (D6 rolled 1-2)',
      rollD6Button: 'Roll D6',
      d6ResultLabel: (roll: number, lost: boolean) => `Rolled ${roll}: ${lost ? 'Lost' : 'Survives'}`,
      none: 'No one from this warband was taken out of action.',
    },
    experience: {
      title: 'Award Experience',
      xpAwarded: 'XP this battle',
      quickAwards: 'Quick awards',
      customAmount: 'Custom amount',
      survivesNote: 'Every participant gets +1 automatically for surviving — already included below.',
    },
    advances: {
      title: 'Resolve Advances',
      thresholdsIntro:
        'Only warriors who crossed an Experience box this battle appear here, and each gets exactly the advances they earned.',
      currentXp: 'Current XP',
      noneEligible: 'Nobody crossed an Experience box this battle, so there are no advances to record.',
      recordedOf: (recorded: number, due: number) =>
        recorded >= due ? `${due} of ${due} advances recorded` : `${recorded} of ${due} advances recorded`,
      removeHint: 'Tap to remove',
      statsAtMax: (stats: string) => `Already at racial maximum: ${stats}.`,
      allStatsMaxed: 'Every characteristic is at its racial maximum — only a new skill can be taken.',
      statAtMaxTitle: (stat: string) => `${stat} is already at its racial maximum.`,
      rerollNeeded: (stat: string) =>
        `${stat} is already at its maximum — roll again for a characteristic that can still be raised.`,
      ladsGotTalent: "That Lad's Got Talent",
      rollButton: 'Roll 2D6',
      rollResultLabel: (total: number) => `Rolled ${total} (2D6):`,
      subRollLabel: (roll: number) => `Roll again (D6): ${roll}`,
      chooseOnePrompt: 'Choose one:',
      specialResultHint: "This app doesn't support this result automatically yet — handle it manually.",
      manualEntryLabel: 'Or record manually',
    },
    deadCleanup: {
      title: 'Dead Models',
      none: 'No models were lost this battle.',
      epitaphLabel: 'Last words or epitaph (optional)',
      epitaphPlaceholder: "e.g. “Tell my mother…”",
      equipmentFate: "What happens to their equipment?",
      toTreasury: 'Send to treasury',
      lost: 'Lost',
      henchmenWipedTitle: (name: string) => `${name} was wiped out`,
      deleteGroup: 'Remove this now-empty group from the roster',
    },
    income: {
      title: 'Income',
      exploration: {
        heading: 'Exploration',
        diceLabel: 'Dice to roll',
        diceHint: (heroes: number, won: boolean) =>
          `${heroes} surviving Hero${heroes === 1 ? '' : 'es'}${won ? ' + 1 for the win' : ''}. Add dice for skills or equipment that grant them.`,
        rollButton: 'Roll the dice',
        rerollButton: 'Roll again',
        editHint: 'Tap a die to change it — for physical dice, a re-roll, or an Elf Ranger’s +1/-1.',
        keepHint: (max: number) => `Only ${max} dice count. Tap to choose which ones.`,
        keptBadge: 'Counts',
        droppedBadge: 'Dropped',
        totalLine: (total: number, shards: number) =>
          `Total ${total} → ${shards} wyrdstone shard${shards === 1 ? '' : 's'}`,
        noMultiple: 'No doubles — nothing found beyond the wyrdstone.',
        foundLabel: 'You found',
        subRollButton: (dice: string) => `Roll ${dice}`,
        subRollResult: (roll: number, result: string) => `Rolled ${roll}: ${result}`,
        applyButton: 'Apply this result',
        clearButton: 'Undo this result',
        appliedGold: (gc: number) => `+${gc} gc added to the treasury.`,
        appliedShards: (n: number) => `+${n} extra shard${n === 1 ? '' : 's'}.`,
        manualNotice: 'The rest of this result is recorded in the battle notes for you to apply by hand.',
        persistentNotice: 'This carries into later games, so it is added to the warband’s notes too.',
        variantNotice: 'Your warband resolves this location differently — the outcome below is the one that applies to you.',
      },
      wyrdstoneFoundLabel: 'Wyrdstone shards found this battle',
      currentStash: (n: number) => `Current stash: ${n} shard${n === 1 ? '' : 's'}`,
      sellLabel: 'Shards to sell now',
      sellPricePreview: (gc: number) => `Sells for ${gc} gc`,
      keepRest: (n: number) => `${n} shard${n === 1 ? '' : 's'} will stay in the warband stash.`,
    },
    upkeep: {
      title: 'Upkeep & Recruiting',
      none: 'No Hired Swords to pay upkeep for.',
      payToggle: (fee: number) => `Pay upkeep (${fee} gc)`,
      insufficientGoldWarning: (needed: number, have: number) =>
        `Total upkeep due is ${needed} gc but the warband only has ${have} gc. You can still proceed — anyone left unpaid will leave the warband.`,
      goToTrading: 'Visit Trading Post',
    },
    confirm: {
      title: 'Confirm & Commit',
      summaryTitle: 'Summary of changes',
      noChanges: 'No changes staged.',
      commitHint: 'Committing writes this battle to the campaign log and updates the warband. You can undo the most recent commit from the roster screen.',
    },
  },
  trading: {
    pickWarbandTitle: 'Trading Post',
    pickWarbandPrompt: 'Which warband is shopping?',
    noWarbands: 'Create a warband first.',
    shopTab: 'Shop',
    rulesTab: 'Trading Rules',
    goldLabel: 'Gold',
    commonTab: 'Common',
    rareTab: 'Rare',
    buyButton: (cost: number) => `Buy (${cost} gc)`,
    groupPurchaseConfirm: (item: string, count: number, total: number) =>
      `Every model in a Henchmen group carries the same gear, so this buys ${count}x ${item} for ${total} gc. Continue?`,
    insufficientGoldConfirm: (cost: number, have: number) =>
      `This costs ${cost} gc but the warband only has ${have} gc. Buy it anyway?`,
    rarityLabel: (n: number) => `Rare ${n}`,
    rollHint: 'This item is found on a result of the Rare number shown, or higher. Roll for me, or roll 2D6 (plus any modifiers) yourself and report the result.',
    rollButton: 'Roll for this item',
    autoRollButton: 'Roll 2D6 for me',
    autoRollResultLabel: (total: number, found: boolean, bonus: number) =>
      bonus
        ? `Rolled ${total} + ${bonus} = ${total + bonus}: ${found ? 'Found it!' : "Didn't find it"}`
        : `Rolled ${total}: ${found ? 'Found it!' : "Didn't find it"}`,
    foundButton: 'Found it',
    notFoundButton: "Didn't find it",
    buyRareNoRollButton: 'Buy (no roll needed)',
    preFirstBattleHint:
      "This warband hasn't fought its first battle yet — per the rulebook, rare items can be bought freely while first assembling a warband. Rolling to find rare items only applies once the campaign is underway.",
    rollBonusHint: (bonus: number) => `Add this warband's +${bonus} bonus before comparing to the Rare number.`,
    priceLabel: 'Price to pay (fill in after rolling any variable dice)',
    confirmPurchase: 'Confirm Purchase',
    treasurySection: 'Treasury',
    treasuryEmpty: 'Nothing in the treasury yet. Buy something above, or it\'ll show up here after a battle.',
    treasuryHint: 'Assign items to a model from the warband roster.',
    sellButton: 'Sell',
    sellPriceLabel: 'Sell price',
    sellConfirm: (name: string, price: number) => `Sell ${name} for ${price} gc?`,
    exclusiveBadge: "Warband-exclusive",
    affordToggle: 'Only what I can afford',
    // Rare prices are a range resolved by a dice roll, so "afford" uses the
    // lowest the item could cost — the filter narrows the list, it doesn't
    // promise the final price.
    affordRareHint: 'Rare items are filtered by their lowest possible price.',
  },
  campaign: {
    title: 'Campaign',
    activityTab: 'Activity',
    settingsTab: 'Settings',
    settingsSection: 'Campaign settings',
    rulesTab: 'Campaign Rules',
    startTitle: 'Start a Campaign',
    startHint: "Set this up once — you can change it later. Battles you commit from the Post-Battle Sequence will log here automatically.",
    nameLabel: 'Campaign name',
    namePlaceholder: 'e.g. Border Town Burning 2026',
    usesBtbLabel: 'Uses Border Town Burning objectives',
    startButton: 'Start Campaign',
    notesLabel: 'Campaign notes',
    battleLogSection: 'Battle Log',
    noBattles: 'No battles logged yet. Play one from the Post-Battle tab.',
    narrative: {
      section: 'Campaign Log',
      hint: 'The story between games — a grudge sworn, a rumour heard, whatever the score sheet misses.',
      titlePlaceholder: 'Entry title',
      bodyPlaceholder: 'What happened…',
      linkBattleLabel: 'Link a battle (optional)',
      noBattleOption: 'No battle',
      add: 'Add entry',
      adding: 'Adding…',
      empty: 'No log entries yet.',
      by: (author: string, when: string) => `${author || 'A player'} · ${when}`,
      linkedTo: (scenario: string) => `On: ${scenario}`,
      remove: 'Remove',
      removeConfirm: 'Remove this log entry?',
    },
    houseRules: {
      section: 'House rules',
      leaderHint: 'Optional rules your group has agreed for this campaign. Only you can change these.',
      memberHint: 'Optional rules the campaign leader has set for this campaign.',
      none: 'Playing the rules as written — no optional rules set.',
      on: 'On',
      off: 'Off',
    },
    recap: {
      concludeSection: 'End of campaign',
      concludeHint: 'Wrap the campaign up: its standings become a final recap. You can reopen it later.',
      concludeButton: 'Conclude campaign',
      concludeConfirm: 'Conclude this campaign? Its standings become a recap. You can reopen it later.',
      reopenButton: 'Reopen campaign',
      concludedBanner: (when: string) => `Campaign concluded ${when}`,
      recapTitle: 'Final recap',
      championLabel: 'Champion',
      shareButton: 'Share recap',
      sharing: 'Building image…',
      shareCaption: (name: string) => `${name} — final standings`,
      standingsHeading: 'Final standings',
      awardsHeading: 'Honours',
      noStandings: 'No battles were logged, so there is no recap to show.',
    },
    announcement: {
      label: 'Announcement',
      hint: 'Pinned to the top of the campaign for everyone. One at a time.',
      placeholder: 'e.g. Next game night is Friday — bring your rosters!',
      pin: 'Pin an announcement',
      save: 'Pin',
      update: 'Update',
      clear: 'Clear',
      clearConfirm: 'Remove the pinned announcement?',
      cancel: 'Cancel',
      posted: (when: string) => `Pinned ${when}`,
    },
    territory: {
      section: 'Territories',
      hint: 'The places your warbands fight over — claim them, and reassign after a battle turns the tide.',
      addButton: 'Add a territory',
      nameLabel: 'Name',
      namePlaceholder: 'e.g. The Marketplace',
      kindLabel: 'Type (optional)',
      kindPlaceholder: 'e.g. Trading, Ruins, Waterfront',
      notesLabel: 'Notes (optional)',
      add: 'Add',
      cancel: 'Cancel',
      empty: 'No territories yet. Add the ones your group fights over.',
      controlledBy: (warband: string) => `Held by ${warband}`,
      unclaimed: 'Unclaimed',
      claimLabel: 'Controlled by',
      remove: 'Remove',
      removeTypeLabel: (name: string) => `Type ${name} to confirm`,
      removeImpact: 'The territory is removed for everyone in the campaign.',
    },
    unknownWarband: 'Unknown warband',
    win: 'Win',
    loss: 'Loss',
    draw: 'Draw',
    underdogBonusLabel: (n: number) => `Underdog bonus: +${n} per survivor`,
    wyrdstoneFoundLabel: (n: number) => `${n} wyrdstone shard${n === 1 ? '' : 's'} found`,
    goldChangeLabel: (n: number) => `${n >= 0 ? '+' : ''}${n} gc`,
    opponentsLabel: 'Opponents',
    casualtiesLabel: 'Casualties',
    notesForBattleLabel: 'Notes',
    btbSection: 'Border Town Burning Objectives',
    btbHint: 'Objectives stay private to you — no one else in the campaign can see them, even for a warband you share.',
    objectiveLabel: 'Objective',
    noObjective: 'None chosen',
    progressLabel: 'Progress (Campaign Points / notes)',
    progressPlaceholder: 'e.g. 12 CP — Prophecy Fulfilled x1',
    completedLabel: 'Objective completed',

    // --- Shared campaigns (spec 8.5) ---
    standingsTab: 'Standings',
    membersTab: 'Players',
    joinTitle: 'Join a Campaign',
    joinAnotherTitle: 'Join another campaign with a code',
    myCampaignsTitle: 'My Campaigns',
    myCampaignsLink: 'All my campaigns',
    inCampaignCount: (n: number) => `You're in ${n} campaigns`,
    myCampaignsEmpty: "You're not in any campaigns yet. Start one or join with a code.",
    activeBadge: 'Showing now',
    playersStat: 'Players',
    battlesStat: 'Battles',
    yourWarbandsStat: 'Your warbands',
    openActive: 'Open campaign',
    switchToThis: 'Switch to this campaign',
    startOrJoinLink: 'Start or join another campaign',
    startAnotherTitle: 'Start another campaign',
    startAnotherHint:
      'You can lead or play in as many campaigns as you like. Each keeps its own battle log, standings and players, and a warband belongs to one at a time.',
    personalBattlesSection: 'Your Battles',
    personalBattlesHint: "Battles you've fought outside a campaign.",
    joinHint: 'Got a code from your campaign leader? Enter it here.',
    joinCodeLabel: 'Join code',
    joinCodePlaceholder: 'MRDH-7F2K',
    joinButton: 'Join Campaign',
    joinFailed: "That code didn't work. Check it with your campaign leader.",
    joinedTitle: (name: string) => `Joined ${name}`,
    orDivider: 'or',
    switchCampaignLabel: 'Current campaign',
    shareCodeSection: 'Invite Players',
    shareCodeHint: 'Share this code so others can join. Anyone with it can enter the campaign.',
    copyCode: 'Copy',
    codeCopied: 'Copied',
    shareWhatsApp: 'WhatsApp',
    shareDiscord: 'Copy for Discord',
    shareDiscordCopied: 'Copied — paste it',
    inviteMessage: (campaignName: string, code: string, url: string) =>
      `Join my Mordheim campaign "${campaignName}" — join code ${code}. Sign up at ${url}, then go to Campaign › Players and paste the code.`,
    // Backticks render the code as inline code in Discord, so it stays legible
    // and survives being read off a phone.
    inviteMessageDiscord: (campaignName: string, code: string, url: string) =>
      `Join my Mordheim campaign **${campaignName}** — join code \`${code}\`\nSign up at ${url}, then go to Campaign › Players and paste the code.`,
    regenerateCode: 'New code',
    regenerateConfirm: 'Issue a new join code? The old one will stop working immediately.',
    deleteBattleConfirm: (scenario: string) =>
      `Remove the ${scenario} entry from the log? Experience and injuries already applied to the warbands stay — this only removes the record.`,
    deleteBattle: 'Remove',
    dangerSection: 'Delete this campaign',
    deleteCampaignBlocked: (n: number) =>
      `${n} other player${n === 1 ? ' is' : 's are'} still in this campaign. Remove them, or let them leave, before deleting it — their battle log and standings go with it.`,
    deleteCampaignImpact:
      'This removes the shared battle log, the standings and every scheduled game night. Warbands are not deleted: they go back to being standalone warbands owned by their players.',
    deleteCampaignTypeLabel: (name: string) => `Type ${name} to confirm`,
    deleteCampaignAction: 'Delete this campaign',
    leaderOnlyHint: 'Only the campaign leader can change these.',
    noCodeYet: 'No code yet',
    membersSection: 'Players',
    roleLeader: 'Leader',
    rolePlayer: 'Player',
    youSuffix: '(you)',
    unnamedPlayer: 'Unnamed player',
    removeMember: 'Remove',
    // Two separate actions, because they differ in what happens to *you* and
    // the old single "Make leader" quietly demoted the person tapping it.
    makeLeader: 'Make co-leader',
    makeLeaderConfirm: (name: string) =>
      `Make ${name} a leader of this campaign as well as you? They can then rename it, regenerate the join code, schedule game nights and remove members — including you. You stay a leader too.`,
    handOver: 'Hand over',
    handOverConfirm: (name: string) =>
      `Hand this campaign to ${name} and step back to being a player? They take over managing it, and you would need them to make you a leader again.`,
    stepDown: 'Step down as leader',
    stepDownConfirm:
      'Give up leading this campaign? You stay in it as a player, and another leader would have to give the role back.',
    removeLeader: 'Remove leader role',
    removeLeaderConfirm: (name: string) =>
      `Take leadership away from ${name}? They stay in the campaign as a player.`,
    onlyLeaderHint:
      'You are the only leader. Make someone else a leader and you can step down — or hand the campaign over in one go.',
    leaderCannotLeave:
      'You lead this campaign. Make someone else a leader first, or it would be left with nobody who can manage it.',
    removeMemberConfirm: (name: string) => `Remove ${name} from the campaign? Their warbands will be unlinked from the standings.`,
    leaveCampaign: 'Leave campaign',
    leaveConfirm:
      'Leave this campaign? Your warbands are withdrawn from its standings — they stay yours, and you can rejoin with the code.',
    standingsSection: 'Standings',
    // §17.4 Awards — a snapshot of the current standings, not a locked-in prize.
    awardsSection: 'Campaign awards',
    awardMostWyrdstone: 'Wyrdstone Baron',
    awardMostWyrdstoneValue: (n: number) => `${n} shard${n === 1 ? '' : 's'} found`,
    awardLongestStreak: 'On a Roll',
    awardLongestStreakValue: (n: number) => `${n} wins in a row`,
    awardMostBattles: 'Old Campaigner',
    awardMostBattlesValue: (n: number) => `${n} battle${n === 1 ? '' : 's'} fought`,
    awardHighestRating: 'Top Dogs',
    awardHighestRatingValue: (n: number) => `rating ${n}`,
    awardMostModelsLost: 'Bloodiest',
    awardMostModelsLostValue: (n: number) => `${n} model${n === 1 ? '' : 's'} lost`,
    awardMostKilled: 'Slayer',
    awardMostKilledValue: (n: number) => `${n} taken out`,
    awardsEmpty: 'Awards appear once a few battles have been fought.',
    // §17.4 (manual) — honours the leader grants by hand, beside the computed
    // "Campaign awards" badges above. Named "Honours" so the two don't collide.
    honours: {
      section: 'Honours',
      hint: 'Awards the campaign leader grants to a warband — Best Painted, MVP, and the like.',
      empty: 'No honours granted yet.',
      add: 'Grant an honour',
      warbandLabel: 'Warband',
      choosePlaceholder: 'Choose a warband…',
      titleLabel: 'Award',
      titlePlaceholder: 'e.g. Best Painted',
      noteLabel: 'Note (optional)',
      notePlaceholder: 'Why it was awarded',
      grant: 'Grant',
      granting: 'Granting…',
      cancel: 'Cancel',
      remove: 'Remove',
      removeConfirm: (title: string) => `Remove the “${title}” honour?`,
      granted: (date: string) => `Granted ${date}`,
      unknownWarband: 'a warband no longer in the campaign',
    },
    // §17.2 Rivalries — head-to-head from the shared battle log.
    activity: {
      section: 'Recent activity',
      empty: 'Nothing has happened here yet.',
      battle: (warband: string, result: string) => `${warband} — ${result}`,
      battleVs: (warband: string, opponents: string, result: string) =>
        `${warband} vs ${opponents} — ${result}`,
      log: (author: string) => `${author || 'A player'} added a log entry`,
      logTitle: (title: string) => `“${title}”`,
      // The title already names the game night; a prefix would double it.
      event: (title: string) => title,
      territory: (name: string) => `Territory claimed — ${name}`,
      territoryBy: (warband: string) => `held by ${warband}`,
      honour: (title: string) => `Honour granted — ${title}`,
      honourTo: (warband: string) => `to ${warband}`,
      announcement: 'Announcement pinned',
      more: (n: number) => `+ ${n} more`,
    },
    rivalriesSection: 'Rivalries',
    rivalriesFor: (name: string) => `${name}'s rivalries`,
    rivalriesEmpty: 'No opponents logged yet.',
    rivalryRecord: (w: number, l: number, d: number) => `${w}W ${l}L ${d}D`,
    rivalryBattles: (n: number) => `${n} battle${n === 1 ? '' : 's'}`,
    // Head-to-head match log, revealed under each rivalry.
    rivalryShardsSwung: (n: number) => `${n} shard${n === 1 ? '' : 's'} found`,
    rivalryMatchShards: (n: number) => `+${n}`,
    rivalryResultWin: 'Win',
    rivalryResultLoss: 'Loss',
    rivalryResultDraw: 'Draw',
    noStandings: 'No players yet.',
    noWarbandEntered: 'No warband entered',
    standingsWarband: 'Warband',
    standingsPlayer: 'Player',
    standingsRating: 'Rating',
    standingsRecord: 'W/L/D',
    viewRoster: 'View roster',

    // --- Warband sharing controls (roster screen) ---
    sharingSection: 'Campaign & Sharing',
    inCampaignLabel: 'Entered in campaign',
    notInCampaign: 'Not entered',
    visibilityLabel: 'Visible outside the campaign',
    visibilityPublic: 'Anyone signed in can view this roster',
    visibilityPrivate: 'Only you (and your campaign) can view this roster',
    campaignMatesAlwaysSee: 'Players in your campaign can always see a warband you enter, whatever this is set to.',
    noCampaignsToJoin: 'Start or join a campaign first to enter a warband in one.',

    // --- Read-only roster of another player's warband ---
    sharedRosterTitle: 'Shared Roster',
    sharedRosterReadOnly: "Read-only — this is another player's warband.",
    sharedRosterOwnHint: 'This is how the rest of the campaign sees your warband.',
    sharedRosterEditMine: 'Open the full roster',
    sharedRosterUnavailable: "You can't view this warband. It may be private, or you may have left the campaign.",
    sharedHeroes: 'Heroes',
    sharedHenchmen: 'Henchmen',
    sharedHiredSwords: 'Hired Swords',
    sharedNoEquipment: 'No equipment',
    sharedNoSkills: 'No skills',
    sharedSkillsLabel: 'Skills',
    sharedInjuriesLabel: 'Injuries',
  },
} as const;
