// All user-facing UI copy lives here so a future translation pass is a
// single-file change. Game-content text (skill effects, injury text, etc.)
// lives in /src/data instead — this file is app-chrome only.

export const strings = {
  appName: 'Mordheim Campaign Manager',
  tagline: 'Offline warband & campaign bookkeeping',
  nav: {
    warbands: 'Warbands',
    postBattle: 'Post-Battle',
    trading: 'Trading',
    campaign: 'Campaign',
    settings: 'Settings',
  },
  common: {
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    back: 'Back',
    add: 'Add',
    gold: 'gc',
  },
  home: {
    warbandCount: (n: number) => `${n} warband${n === 1 ? '' : 's'} stored on this device`,
    noCampaign: 'No campaign started yet',
  },
  settings: {
    title: 'Settings',
    dataSection: 'Your Data',
    exportButton: 'Export all data (.json)',
    importButton: 'Import data from file',
    importOverwriteWarning: 'Importing will overwrite all warbands and campaign data currently stored on this device. This cannot be undone. Continue?',
    importSuccess: 'Import complete.',
    importError: (message: string) => `Import failed: ${message}`,
  },
  placeholder: {
    comingSoon: (feature: string) => `${feature} is coming in a later milestone.`,
  },
  warbandList: {
    title: 'Warbands',
    empty: 'No warbands yet. Create one to get started.',
    newWarband: '+ New Warband',
    ratingLabel: 'Rating',
    goldLabel: 'Gold',
    shardsLabel: 'Shards',
  },
  newWarband: {
    title: 'New Warband',
    nameLabel: 'Warband name',
    namePlaceholder: 'e.g. Grubnik\'s Maneaters',
    typeLabel: 'Warband type',
    createButton: 'Create Warband',
    nameRequired: 'Give your warband a name first.',
  },
  roster: {
    heroesSection: 'Heroes',
    henchmenSection: 'Henchmen Groups',
    hiredSwordsSection: 'Hired Swords',
    noHeroes: 'No heroes yet.',
    noHenchmen: 'No henchmen groups yet.',
    noHiredSwords: 'No hired swords yet.',
    addHero: '+ Add Hero',
    addHenchmen: '+ Add Henchmen',
    goldLabel: 'Gold',
    shardsLabel: 'Wyrdstone Shards',
    ratingLabel: 'Warband Rating',
    deleteWarband: 'Delete Warband',
    deleteWarbandConfirm: (name: string) => `Delete "${name}" and all its heroes, henchmen, and history? This cannot be undone.`,
    slotLimitWarning: (unitType: string, max: number) =>
      `Your warband already has the normal maximum of ${max} ${unitType}(s). Add another anyway?`,
    missNextGameBadge: 'Miss Next Game',
    deadBadge: 'Dead',
    capturedBadge: 'Captured',
    leftBadge: 'Left Warband',
  },
  addHero: {
    title: 'Add Hero',
    pickSlot: 'Choose a hero type',
    nameLabel: 'Name',
    namePlaceholder: "e.g. Grubnik",
  },
  addHenchmen: {
    title: 'Add Henchmen',
    pickType: 'Choose a henchman type',
    groupNameLabel: 'Group name',
    groupNamePlaceholder: 'e.g. Gnoblar Mob',
    countLabel: 'Number of models',
    addToExisting: 'Add to an existing group instead',
    newGroup: 'Start a new group',
  },
  modelDetail: {
    statsSection: 'Characteristics',
    atMax: 'At racial max',
    xpSection: 'Experience',
    xpTotal: 'Total XP',
    recordAdvance: 'Record Advance',
    advanceTypeStat: 'Characteristic Increase',
    advanceTypeSkill: 'New Skill',
    pickStat: 'Which characteristic increased?',
    pickSkillList: 'Which skill list?',
    pickSkillName: 'Skill name',
    skillNamePlaceholder: 'e.g. Strongman',
    skillsSection: 'Skills',
    noSkills: 'No skills learned yet.',
    injuriesSection: 'Injuries',
    noInjuries: 'No injuries recorded.',
    addInjury: '+ Add Injury',
    injuryNameLabel: 'Injury name',
    injuryEffectLabel: 'Effect',
    missNextGameLabel: 'Miss next game',
    equipmentSection: 'Equipment',
    noEquipment: 'Nothing equipped.',
    treasurySection: 'Warband Treasury',
    noTreasury: 'Treasury is empty.',
    moveToTreasury: 'Move to treasury',
    assignToModel: 'Assign here',
    statusLabel: 'Status',
    notesLabel: 'Notes',
    deleteModel: 'Remove from Warband',
    deleteModelConfirm: (name: string) => `Remove ${name} from the warband? This cannot be undone.`,
  },
  postBattle: {
    pickWarbandTitle: 'Post-Battle Sequence',
    pickWarbandPrompt: 'Which warband fought this battle?',
    noWarbands: 'Create a warband first.',
    startButton: 'Start Post-Battle Sequence',
    stepOf: (step: number, total: number) => `Step ${step} of ${total}`,
    next: 'Next',
    commitBattle: 'Commit Battle',
    undoLastBattle: 'Undo Last Battle',
    undoConfirm: 'Revert the warband and campaign log to how they were before the last post-battle sequence was committed?',
    battleInfo: {
      scenarioLabel: 'Scenario',
      scenarioCustom: 'Other / not listed…',
      scenarioCustomLabel: 'Scenario name',
      opponentsLabel: 'Opponent warband(s)',
      opponentsPlaceholder: 'e.g. Marius Dire\'s Undead',
      resultLabel: 'Result',
      win: 'Win',
      loss: 'Loss',
      draw: 'Draw',
      dateLabel: 'Date',
      underdogLabel: 'Underdog bonus (per surviving model)',
      underdogHint: 'From the rulebook\'s underdog table: 0 if the rating gap is 0-50, +1 for 51-75, +2 for 76-100, +3 for 101-150, +4 for 151-300, +5 for 301+.',
      notesLabel: 'Battle notes',
    },
    injuries: {
      sittingOut: 'Sitting out this game (missed last game\'s penalty).',
      outOfActionToggle: 'Taken out of action this battle',
      rollInjury: 'Roll on the injury table',
      addAnotherRoll: '+ Add another roll (Multiple Injuries)',
      statusLabel: 'Resulting status',
      henchmenOutOfAction: 'Models taken out of action',
      henchmenDied: 'Of those, how many died? (D6 per model: 1-2 dead)',
      hiredSwordLostHint: 'Hired Swords use the Henchmen rule: roll a D6, 1-2 = lost, 3-6 = survives.',
      hiredSwordLostToggle: 'Lost (D6 rolled 1-2)',
      none: 'No one from this warband was taken out of action.',
    },
    experience: {
      title: 'Award Experience',
      xpAwarded: 'XP this battle',
      quickAwards: 'Quick awards',
      customAmount: 'Custom amount',
      survivesNote: 'Every participant gets +1 automatically for surviving — already included below.',
    },
    advances: {
      title: 'Resolve Advances',
      unknownThresholds: "This app doesn't yet have the exact XP thresholds from your roster sheet — check your sheet for who's crossed a thick-bordered box, then record their advance here.",
      currentXp: 'Current XP',
      noneEligible: 'No one gained XP this battle.',
    },
    deadCleanup: {
      title: 'Dead Models',
      none: 'No models were lost this battle.',
      equipmentFate: "What happens to their equipment?",
      toTreasury: 'Send to treasury',
      lost: 'Lost',
      henchmenWipedTitle: (name: string) => `${name} was wiped out`,
      deleteGroup: 'Remove this now-empty group from the roster',
    },
    income: {
      title: 'Income',
      wyrdstoneFoundLabel: 'Wyrdstone shards found this battle',
      currentStash: (n: number) => `Current stash: ${n} shard${n === 1 ? '' : 's'}`,
      sellLabel: 'Shards to sell now',
      sellPricePreview: (gc: number) => `Sells for ${gc} gc`,
      keepRest: (n: number) => `${n} shard${n === 1 ? '' : 's'} will stay in the warband stash.`,
    },
    upkeep: {
      title: 'Upkeep & Recruiting',
      none: 'No Hired Swords to pay upkeep for.',
      payToggle: (fee: number) => `Pay upkeep (${fee} gc)`,
      insufficientGoldWarning: (needed: number, have: number) =>
        `Total upkeep due is ${needed} gc but the warband only has ${have} gc. You can still proceed — anyone left unpaid will leave the warband.`,
      goToTrading: 'Visit Trading Post',
    },
    confirm: {
      title: 'Confirm & Commit',
      summaryTitle: 'Summary of changes',
      noChanges: 'No changes staged.',
      commitHint: 'Committing writes this battle to the campaign log and updates the warband. You can undo the most recent commit from the roster screen.',
    },
  },
} as const;
